### ISSUE TITLE
Import Shimmer GSR+ data

### ISSUE THREAD

**Issue by marklindquist** [bachlab/PsPM#109]
Is it possible to import data directly that is collected using the Shimmer GSR+ hardware:
https://www.shimmersensing.com/products/shimmer3-wireless-gsr-sensor

Thanks for any information.

**Comment by Noldos** [comment]
Hi marklindquist,

I pushed a hotfix that should allow you to do this.  49fc8d1
From consensys, export the data as .txt (extension has to be .txt if you are using the GUI) using any delimiter you like. you will have to specify the sampling rate, and channel number by hand. I think the transfer function can be set to none if you export the data "calibrated" (I didn't check).

If you're not using consensys, you can export it from any other software as coma separated values file and import it as above. Note that by default only spacing character separated values are recognized (space, tab or backspace). if you'd like to use any others, the first line of the .csv has to be `"sep=<your delimiter of choice>"`, so, for semi-colon separated values, it would be `"sep=;"` (including the double quotes). 

There is currently no Shimmer specific import method, but it might be added in the future.

Let me know if this works or if there are any issues with this.

**Comment by irojkov-ph** [comment]
Since no new messages were published for 22 days, I close this issue.
The hotfix 49fc8d1 will be available until #110 is not closed. For any new issue concerning the hotfix send a message in #110.
Ivan.
