### ISSUE TITLE
Add support for Delimiter Separated Values data files

### ISSUE THREAD

**Issue by Noldos** [bachlab/PsPM#110]
### Feature Description
The goal is to be able to import **Delimiter Separated Values**, particularly .csv and .tsv

### How
Modify .txt import so as to allow for delimiters that are non matlab standard (white space, backspace, tabulator). One way would be to use the excell switch (which we have to handle anyways): "sep=<delimiter>" in the first line of the file. But this is non standard dsv. I'll implement this as a quick fix for #109 

In addition, we might want to switch on the file extension and assume delimiters based on this. 
This raises the issue that there does not seem to be an accepted standard. while .tsv is not unheard of, .ssv is quite obscure and most semi-colon dsv are saved as .csv, meaning sanity checks would have to be implemented. 

| extension | delimiter |
|-|-|
|.csv|, (coma)|
|.tsv|\t (tab)|
|.psv|\| (pipe)|
|.ssv|; (semi-colon)|
 
An other option would be to pass the separator as an argument to the function. this would mean that GUI and parent functions would have to be adapted

### Questions
- which of these options should be implemented?
- would we replace the text import function or create a new import?

**Comment by irojkov-ph** [comment]
I think we should stick to the standard way of approaching this problem, that means implement the last option you've proposed:
> An other option would be to pass the separator as an argument to the function. this would mean that GUI and parent functions would have to be adapted

**Comment by irojkov-ph** [comment]
Do you want to do it or should I ?

**Comment by irojkov-ph** [comment]
Maybe it  would be easier to implement it with the `readtable` function from MATLAB
https://ch.mathworks.com/help/matlab/ref/readtable.html
