### ISSUE TITLE
SCR import failed: Output argument "data" (and maybe others) not assigned during call to "pspm_get_marker".

### ISSUE THREAD

**Issue by mengzeli123** [bachlab/PsPM#114]
there are 2 of my SCR data that cannot be import in PSPM.

11-May-2020 11:19:45 - Failed  'Import'
Output argument "data" (and maybe others) not assigned during call to "pspm_get_marker".
In file "C:\Users\klaud\Documents\toolbox\PsPM\src\pspm_import.m" (???), function "pspm_import" at line 220.
In file "C:\Users\klaud\Documents\toolbox\PsPM\src\pspm_cfg\pspm_cfg_run_import.m" (???), function "pspm_cfg_run_import" at line 97.

If possible, could you tell me the reason why something might go wrong here?

**Comment by irojkov-ph** [comment]
Hi @mengzeli123 
This could come from various reasons. My main guess would be that you are trying to import data of a type which is not supported by PsPM, but maybe I am wrong. Can you please tell me what you want to import ? If you can also provide me that data it would be great !
Ivan.
