### ISSUE TITLE
Check the importion of markers when using 'windaq_n' function

### ISSUE THREAD

**Issue by irojkov-ph** [bachlab/PsPM#115]
### Summary
While importing some windaq data (using `windaq_n` function), it have been noticed that the marker channel imports the `markerinfo` field with some non-constant 'name' and 'value' data which is an unexpected behavior.

### Example
Check out the data in the zip folder for more details.
[examples.zip](https://github.com/bachlab/PsPM/files/4675870/examples.zip)

### Expected Results
Ideally `windaq_n` function should create constant values in the `markerinfo` field.

### (Optional) Possible Cause and Solutions
Maybe it is proper to this data set (cf. raw HRM1-2) or a more general problem related to the `windaq_n` function itself.

### Technical Info
* PsPM revision ID: (last one)
* MATLAB version: 2019b

**Comment by sammaxwellxyz** [comment]
Hey @irojkov-ph  , apologies, I'm having difficulty in replicating, could you give me some steps?

**Comment by sammaxwellxyz** [comment]
Hey @irojkov-ph could you share with me the raw HRM1-2 data set?

**Comment by sammaxwellxyz** [comment]
Hey @irojkov-ph , dominik gave me the HRM1-2 data so Ive have that to play with, I chose a data set that seemed to have some non constant values, I looked at HRM_1_23.wdq and pspm_HRM_1_23.mat. The pspm_HRM_1_23.mat I was provided had the non-constant values from what I can tell, approx 20 names and values of either 0 or 4. When I re-ran the import on HRM_1_23.wdq (using the non-activeX import), I got approx 20 names and values but ALL were 4. I used channel 1 as the scr, 2 as ecg, and 3 as marker. Could you give me some steps to reproduce? I'm really hoping this isn't a version or OS problem :(.
Cheers

**Comment by sammaxwellxyz** [comment]
This issue seems to be down to the offsetting values used for the descending option.

https://github.com/bachlab/PsPM/blob/develop/src/pspm_get_events.m

L78
L93
L122

I think this is the commit that introduced the bug https://github.com/bachlab/PsPM/commit/73855ff386cdcd8446317a25e252f8b527d35b2f

from my testing it seems the fix is to change L81 from `mPos = hi2lo+2;` to `mPos = hi2lo+3;` to align with the index shift made in that commit.
