### ISSUE TITLE
New scanpath GUI items

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#120]
### New matlabbatch items:
1. Remove 'convert data' from data preprocessing
2. Add 'pupil size preprocessing' to data preprocessing (may need a better name as there is already a 'pupil preprocessing'
3. Add 'pupil gaze preprocessing' to data preprocessing
4. GLM for scanpath speed
5. both to be implemented in the "red" GUI as well

**Comment by sammaxwellxyz** [comment]
@dominikbach for point number 1, is this a kind of a convenience method? It seems as though there exists a 'convert data', option under pre-processing which can achieve pixel to degrees, and visangle to scanpath, therefore could be acheived using the convert data. Are the 'degrees' the same as the visangle?
