### ISSUE TITLE
pspm_simple_qa: epoch output path

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#128]
### Feature Description

Use full path for saving epoch output file, don't change file extension (i.e. if no file extension then add 'mat' and if there is one then keep it - this is the behaviour of matlab's 'save') and ask for path in GUI (similar to model file user interaction for pspm_glm)

**Comment by sammaxwellxyz** [comment]
I believe this is already completed, or maybe I don't understand the issue. I was able to write out an epoch file using a full path without .mat extension

**Comment by sammaxwellxyz** [comment]
I believe this one may have already been completed, I was able to save an epoch file using a full path and not including a .mat extension. Or maybe I don't understand the issue

**Comment by dominikbach** [comment]
Indeed, current behaviour of pspm_simple_qa is as required, so there is nothing to do in the function.

In the matlabbatch, we still need to add an item for the output directory, in addition to the filename (similar to model file/ouput directory for GLM).
