### ISSUE TITLE
Analysis of multiple events per trial

### ISSUE THREAD

**Issue by kknauth** [bachlab/PsPM#137]
Hey everybody,

I´m interested in modeling pupil responses to images from three different categories, so there are three experimental conditions. Every trial starts with the presentation of an image which remains on screen for 5 seconds in total. 2 seconds post image onset, another stimulus is superimposed on the image. There are also three types of this second stimulus (e.g. easy, medium, hard type).
I would like to examine three different things:
Does pupil response following image onset differs depending on image category (1. trial event)
Does pupil response following the 2. stimulus onset differs depending on stimulus type (easy, medium hard; 2. Trial event)
Are there any interaction effects.

So my question would be: Is it possible to set up a model with pspm which is capable to capture those effects despite there are multiple events per trial, and despite the fact it´s no classical fear conditioning paradigm? If yes, are there any tutorials covering such “more complicated” models?
I have watched some of your very helpful tutorials but they were not 100% suited to my problem.

Thank you in advance and kind regards =)
Kilian

**Comment by dominikbach** [comment]
Hi Kilian
sorry for the late reply.
I'm afraid there is no simple model of arousal-induced pupil responses in PsPM or in the wider literature. 
PsPM contains models for luminance-related responses, and fear-conditioned pupil responses. I'm not aware of any other models that are validated on more than a handful of subjects.
I guess in this case, your best bet is to do "forward modelling", i.e. assume the time course is unknown and test for condition differences in a cluster-based random permutation test (see e.g. Oostenveld et al. 2007). 
To do so, you can average responses over trials using the "extract segments" feature.
Hope this helps
Dominik

**Comment by kknauth** [comment]
Hey Dominik,
thanks for your very helpful remarks on that forward modeling approach! I will give it a try.

All the best!
Kilian
