### ISSUE TITLE
Is it possible to analyze the non-startle-related event-related EMG?

### ISSUE THREAD

**Issue by iPsych** [bachlab/PsPM#142]
### Feature Description
Hello, is it possible to analyze the non-startle-related EMG, which event-related but already integrated in elsewhere.
It will be really great to analyze the integrated event-related EMG data with other modality within PSPM.

**Comment by dominikbach** [comment]
In principle, this is possible. However, no models for such EMG responses are implemented in PsPM, and we are not aware of any such models, or standardised peak-scoring guidelines to build on, in the wider literature. 

This is a field we plan to expand in, and if you have any relevant data and would like to develop a model, we would be more than happy to support you.

Dominik
