### ISSUE TITLE
Rewrite/reorganise pspm_extract_segments in a cleaner way

### ISSUE THREAD

**Issue by irojkov-ph** [bachlab/PsPM#144]
### Feature Description
With the functionality implemented in #83 one can extract segments from any type of data now. However, the current implementation of the function is messy and do not allow to add any extension to it in a clean way. The goal is then to reorganise it and rewrite some parts of it. Mainly:
- [ ] keep only the 'manual' mode as the main mode of this function
- [ ] rewrite + add some parameters check (to avoid future bugs)
- [ ] create two new functions `pspm_extract_segments_glm` and `pspm_extract_segments_dcm` which are currently implemented in the main function + rewrite them to make use of `pspm_extract_segments` function
- [ ] in the two latter functions add an option which allows the user to select which data (raw, filtered, reconstructed, ...) should be used to extract segments from (cf. #22 )
- [ ] add the latter option in the GUI

**Comment by dominikbach** [comment]
Fixed by #641.
