### ISSUE TITLE
Help needed with non-linear SCR analysis (pspm_dcm)

### ISSUE THREAD

**Issue by blue-vv** [bachlab/PsPM#167]
### Summary
To whom it may concern,

Thank you very much for making PsPM openly available.

I'm trying to run non-linear SCR analysis, but it stops with the following error. 

------------------ error message ---------------------------
Could not find any enabled trial for file '(filename).mat' 
> In pspm_dcm (line 574)
--------------------------------------------------------------

This seems to be due to that a variable "trialinfo" is an array of 0s and "subs" is an array of -1s. (line 538 in pspm_dcm)

When I tried to run the same batch script as above with a tutorial data file (tpspm_s1.mat) and an tutorial event file (event_timings_s1.mat) from Tutorial_dataset_DCM, it worked fine (and "trialinfo" and "subs" were both arrays of 1s, instead of 0s and -1s in my case above). This makes it more likely that my data/event files contain some issues.

However, when I compare the data files and event files between my own and tutorial data set, I'm failing to detect any critical differences. Could you please help me find what's causing the issue?

Thank you very much for your support in advance.

### Technical Info
* PsPM revision ID: 5.0.0
* MATLAB version: R2018b

**Comment by blue-vv** [comment]
My apologies. This seems to be now solved. The issue was not in my data file (which I was scrutinizing) but was in my event file (having many duplicated time stamps). Thank you for your attention, regardless.

**Comment by irojkov-ph** [comment]
Hi @blue-vv,
Happy to hear that you found the solution by yourself! :) 
If you have any other questions or suggestions, do not hesitate, we will be glad to help you ;)
I close this issue for now.
Cheers,
Ivan.
