### ISSUE TITLE
filtering before GLM?

### ISSUE THREAD

**Issue by mm390** [bachlab/PsPM#169]
Hi,
I'm analyzing SCR data with PsPM and I would like to know if filtering the raw data should be done before modeling with GLM. 
It seems that during GLM the design matrix is filtered anyway, so is it necessary/recommended that we do it before GLM?
Thanks!

**Comment by dominikbach** [comment]
Hi there

PsPM filters the data and the design matrix with the same filters. The filter default was optimised in Bach et al. 2013 (attached). If you require different filter values, then the recommendation is to use unfiltered data and change the filter values in the GLM setup, as this ensures the design matrix is filtered in the same way.

Hope this helps
Dominik
[Uploading Bach et al. 2013 BiolPsychol SCR_GLM_Development.pdf…]()
