### ISSUE TITLE
'Non-linear model'/DCM-model take very long time to analyze 

### ISSUE THREAD

**Issue by andgad** [bachlab/PsPM#171]
### Summary

Dear, 

After I fixed my timing files I started the analysis of the data using the 'non-linear model'/DCM-model but it took a very long time, more than 24 hours and then the computer crashed. Do you have any suggestions except buying a new computer with more resources how I can use the non-linear model anyway? 

Best
Anders 

### Technical Info
* PsPM revision ID: 5.0.0 (21.08.2020)
* MATLAB version: R2019b

**Comment by dominikbach** [comment]
24 hrs sounds very long, but it depends on your system specs and the data type. There may be some possibility of tweaking performance. Can you give us some details:
- how long is the SCR recording? 
- how long is the longest break between any two trials in a single session? what is the average ITI?
- what processor (and how many of them) does your computer use?

**Comment by andgad** [comment]
Hi Dominik, 

Thank you so much for your answer!

- The recording is 2500seconds long (an fMRI experiment was done at the same time)
- ITI is 26-34seconds, mean 30seconds. Don't know about the longest break. 
- MacBook Air: 1,6 GHz Dual-Core Intel Core i5

As it is now it seems unworkable to batch with many participants which is a pity since the DCM-model according to the manual and your answers to other peoples' questions, seemed to be the best model for the design. So any tip to make it doable is gladly received. 

Best
Anders

**Comment by dominikbach** [comment]
Hi Anders
if this was an fMRI experiment then was it perhaps split up into acquisition runs, with scanner-off breaks inbetween?
It could be useful to split up the SCR data as well to speed up DCM.
The long ITIs and any long breaks are going to be the time-consuming part, because the default is to model 1 SF per 2 s of data during ITIs - this can result in many more parameters to be estimated than during trials. 
Best
Dominik

**Comment by andgad** [comment]
Hi Dominik,

Yes the experiment was made up of four runs. I will try to split them up to see if that will enhance the speed of the analysis.
If you have any instructions of the settings for the DCM-model other than in the PSPM-manual I would gladly receive it?

Best
Anders
