### ISSUE TITLE
Make pspm_simple_qa independent from pspm_pp

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#173]
### Background
(1) pspm_pp is a generic function for various channel types. It expects that data are changed and will always output a new file.
(2) pspm_simple_qa is a function specifically for SCR data; it may create changed data or just artefact epoch files
(3) other channel-type specific functions are named pspm_..._pp, e.g. pspm_pupil_pp, pspm_emg_pp

### Requested features
(1) Rename pspm_simple_qa into pspm_scr_pp
(2) Call pspm_scr_pp directly rather than through pspm_pp (requires adding file I/O)
(3) Change Matlabbatch GUI to reflect this
(4) If change_data = 0, do not write a new data file

**Comment by teddychao** [comment]
@dominikbach Can I know the full name of _scr_ in pspm_scr_pp here? Then I can update the description of pspm_scr_pp. Thanks!
