### ISSUE TITLE
Find out minimum MATLAB version

### ISSUE THREAD

**Issue by eozd** [bachlab/PsPM#20]
### Feature Description
Find out the minimum MATLAB version that can run support whole PsPM functionality. Current development is being done on R2018b, but we should be able to support much earlier version such as 2013.

**Comment by fmelinscak** [comment]
This could be achieved using the build matrix Jenkins functionality, once we have that up and running; e.g. see here: https://blogs.mathworks.com/developer/2017/09/26/the-build-matrix-laboratory/
I think it'd make sense to agree on how many iterations of backwards compatibility we want, and then when new versions of Matlab come out, add them to the build matrix and eliminate the oldest version.

**Comment by irojkov-ph** [comment]
Maybe that could help:
`[fun_dep , packages_dep] = atlab.codetools.requiredFilesAndProducts('pspm_trim.m')`
`pspm_trim.m` is just an example.

**Comment by fmelinscak** [comment]
Well, this tool tells you the toolbox dependencies, but it doesn't tell you the backward compatibility unfortunately:
"The version numbers indicate the version of the products you have installed when you execute the function. Version is not an indicator of backward compatibility."
So, it wouldn't be a way around actually testing with different Matlab versions.

**Comment by sammaxwellxyz** [comment]
Regarding "but we should be able to support much earlier version such as 2013." is this a requirement?
It'd be good to understand how many versions we should be supporting, even if we don't have the CI integrations working to test multiple versions, we could at least use that information when writing code.

For example, I was looking at argument validation today, https://uk.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html#mw_b60f7a04-8db1-4408-9918-80b171169139, which looks like a nice way to handle validation and defaulting, however the 'arguments' syntax was only supported introduced from 2019b. I recognise this may well be too new to require users to have but knowing the level would be great.

Is there a way to contact all users and potentially survey as to what version they use?
Do we have users that are non-academic / likely to be paying for a license?

**Comment by irojkov-ph** [comment]
> Regarding "but we should be able to support much earlier version such as 2013." is this a requirement?

I would say no but the earliest is the best I guess. It mostly depends on the answer of this question:

> Do we have users that are non-academic / likely to be paying for a license?

And I would think that there are some labs around the world which pays the license and which doesn't want to switch to a newer one for this reason. But one can (if Dominik agrees of course) say that PsPM is available for Matlab version >= 9.0 for instance and keep increasing this number over time. It's not user friendly but it could be argued that it's Matlab fault xD

> Is there a way to contact all users and potentially survey as to what version they use ?

This I think is very difficult, could be nice to have an option to send a message through Matlab's interface to all the users that have PsPM but I am pretty sure it's not possible.

> For example, I was looking at argument validation today, https://uk.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html#mw_b60f7a04-8db1-4408-9918-80b171169139, which looks like a nice way to handle validation and defaulting, however the 'arguments' syntax was only supported introduced from 2019b. I recognise this may well be too new to require users to have but knowing the level would be great.

Nice feature but too early to use it I guess (or at least in crucial PsPM functions)

**Comment by irojkov-ph** [comment]
Test
\poll Yes 'No'

**Comment by irojkov-ph** [comment]
Sam's handover comment:

> Having spoken to Guillame Flandin at SPM they had not developed a cloud solution to cater for all matlab versions back to a set upon version. Matlab themselves only offer versions back to 2017 for download, it is quite feasible to get all versions onto the CI server and have Jenkins run the tests for each using the path of the install for each. Guillame had also strongly suggested refactoring to support Octave, I had a very brief crack to see if this was possible but failed on the first hurdle as octave doesn't support the 'import' functionality used in the tests.

**Comment by teddychao** [comment]
The current minimum version of MATLAB required for running PsPM is 7.1.

**Comment by dominikbach** [comment]
@teddychao can we close this?

**Comment by dominikbach** [comment]
run github actions on a 4-year old matlab version?

**Comment by teddychao** [comment]
@dominikbach Sorry I just see this update. I have created a branch that added the minimum MATLAB version requirement in the manual. Thanks
