### ISSUE TITLE
pspm_extract_segments should not read data from model.datafile field

### ISSUE THREAD

**Issue by eozd** [bachlab/PsPM#21]
### Feature Description
Reading the data by loading the file at `model.datafile` field makes the function not compatible with multiple operating systems or different filesystems. Since all the required data should already be stored in GLM or DCM output structures, the whole logic of the function can be simplified significantly while making it more robust.

**Comment by irojkov-ph** [comment]
Is it solved by #83 ? Or do you mean something else ?

**Comment by eozd** [comment]
I think this is one of the older issues, so I am not sure if it still persists. But the problem was that extract segments would load the data from the filepath specified in glm or dcm structure instead of using the data which is already stored in the structure. This doesn't seem to be the case now. Could you confirm that?

**Comment by irojkov-ph** [comment]
I am going through all the issues right now in preparation for the future release.

For this one, I confirm that if you use glm option the function does not load the data from `model.input.datafile` but uses directly the data stored in the glm structure. Thus I close the issue.
