### ISSUE TITLE
plot of design matrix of pupil size glm with luminance as nuisance file

### ISSUE THREAD

**Issue by SerenXia** [bachlab/PsPM#213]
### Summary
1. PsPM GUI first-level model review should use glm.XM when plotting design matrix, but not glm.X
2. design matrix plot did not show the correct design matrix (see attachments), but the design orthogonality plot seemed correct
![CFG_day1_ps_nuisance_design_matrix_0001](https://user-images.githubusercontent.com/67365315/116868211-adc7bc80-ac0e-11eb-9973-bf4c31d506ad.jpg)
![CFG_day1_ps_nuisance_design_orthogonality_0001](https://user-images.githubusercontent.com/67365315/116868218-aef8e980-ac0e-11eb-8b63-d701cdf30109.jpg)
![CFG_day2_ps_nuisance_design_matrix_0001](https://user-images.githubusercontent.com/67365315/116868221-aef8e980-ac0e-11eb-8081-945cb7e8b755.jpg)
![CFG_day2_ps_nuisance_design_orthogonality_0001](https://user-images.githubusercontent.com/67365315/116868224-aef8e980-ac0e-11eb-9169-72af40e42436.jpg)
[mdl_ps_fc_tpspm_exampledata.zip](https://github.com/bachlab/PsPM/files/6414397/mdl_ps_fc_tpspm_exampledata.zip)

### (Optional) Screenshots if Graphical User Interface is Used
please see attachments

### Technical Info
* PsPM revision ID: model inversion done in v5.0.0 (latest released version by 03.05.2021); model review done in PsPM GUI called from version "pspm-svn-r801-trunk".
* MATLAB version: 2018b

**Comment by teddychao** [comment]
Comments are given [here](https://github.com/bachlab/PsPM/pull/223#pullrequestreview-682597470)

**Comment by SerenXia** [comment]
I am reopening this issue because the design matrix of pupil size glm model with luminance as nuisance file is still not correct.

Details please see comments here: [https://github.com/bachlab/PsPM/pull/223#pullrequestreview-682597470](url)

**Comment by teddychao** [comment]
Hi @SerenXia , may I confirm with you that the issue still there is referring to this plot? 
As I understand from your comments, plot is incorrect because the design matrix remains the same for different trials? However, individually, the design matrix itself for one trial looks correct?
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/3895146/135842068-87e8e18d-d205-4056-acaa-745989e330b4.png">

**Comment by SerenXia** [comment]
> Hi @SerenXia , may I confirm with you that the issue still there is referring to this plot? As I understand from your comments, plot is incorrect because the design matrix remains the same for different trials? However, individually, the design matrix itself for one trial looks correct? <img alt="image" width="1264" src="https://user-images.githubusercontent.com/3895146/135842068-87e8e18d-d205-4056-acaa-745989e330b4.png">

exactly

**Comment by teddychao** [comment]
> > Hi @SerenXia , may I confirm with you that the issue still there is referring to this plot? As I understand from your comments, plot is incorrect because the design matrix remains the same for different trials? However, individually, the design matrix itself for one trial looks correct? <img alt="image" width="1264" src="https://user-images.githubusercontent.com/3895146/135842068-87e8e18d-d205-4056-acaa-745989e330b4.png">
> 
> exactly

Hi Yanfang,

Thank you. May I confirm with you about the two files you sent to me last time? For the files _mdl_ps_fc_tpspm_CFG10001_ and _mdl_ps_fc_tpspm_CFG10002_, are they two trials, like trial 10001 and trial 10002?

Thanks.

Best wishes,
Teddy
