### ISSUE TITLE
pspm_extract_segments should handle filtered and reconstructed data

### ISSUE THREAD

**Issue by eozd** [bachlab/PsPM#22]
### Feature Description
`pspm_extract_segments` currently only supports segment extraction from raw data. But extracting the segments from other datatypes such as filtered and reconstructed are also important functionalities.

**Comment by irojkov-ph** [comment]
Why is it a problem to extract segments from such datatypes ?

**Comment by eozd** [comment]
It is not a problem per se; however, in a glm structure we have all three of these data versions. If I remember correctly extract segments only uses the raw data in that case. With the functionality implemented in #83 one can perform this operation on any type of data a bit more easily now, but an automatic way of performing this for all data versions in glm structure is still missing. Regardless, I do think that we need a complete rewrite of `pspm_extract_segments` at some point, as the implementation is way too bulky to be maintained or extended at this point.

**Comment by irojkov-ph** [comment]
I am going through all the issues right now in preparation for the future release.

For this one I've created a new, more general issue #144 which should be done for the next big release I think. For now I close this one.
