### ISSUE TITLE
Endless loop of converting ECG to Heart Beat in pspm_ecg2hb

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#227]
@SerenXia mentioned there could be a problem that leads to endless loops in the function pspm_ecg2hb.m.

This problem could be resolved manually by selecting an alternative algorithm.
- Not working with *Pan & Tompkins*
- Working with *AMRI*

<img width="266" alt="image" src="https://user-images.githubusercontent.com/3895146/118837336-9b12e000-b8bc-11eb-8894-a16f2a50e0c6.png">

**Comment by dominikbach** [comment]
No data available to reproduce.
