### ISSUE TITLE
pspm_split_session.m missed the last trial in the block

### ISSUE THREAD

**Issue by SerenXia** [bachlab/PsPM#228]
### Summary
The current pspm_split_session.m fixed the previous bug reported (i.e. adding additional trials from the next block to the current block, closed issue #198), but for some data it missed the last trial of the current block.

For example, I have 88 trials in 4 blocks, so 22 each. But the function is spliting the data file into 4 sessions, with 22, 22, 21, and 21 trials, namely, the last trial in the third and the fourth trial were not included.

Example data will be sent via email.

### Technical Info
* PsPM revision ID: 5.0.0 (but the split_session function was from the current develop branch)
* MATLAB version: 2018b

**Comment by teddychao** [comment]
Experimental [data](https://liveuclac-my.sharepoint.com/:u:/g/personal/skgtdz0_ucl_ac_uk/EbgAY3S95V5Bojlpra4n9GEBaARY0zO0IyeNt60K6Klj7w?e=A1zPTX) can be found with a UCL account.

**Comment by dominikbach** [comment]
@SerenXia could you kindly check whether #252 fixes this?
