### ISSUE TITLE
List of features requested for PsPM version 5.1.0 

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#229]
Based on the latest discussion, PsPM version 5.1.0 would be released in mid June. Apart from the issues that have been fixed in the current develop branch, the following issues must be fixed 
- Issue #220 
- Issue #214 
- Issue #133 
- Issue #173 
- UI improvement

The following issues can be fixed as many as possible if there is enough time
- Issue of brain vision data importing
- Issue #213 
- Issue #206 
- Issue #224

**Comment by teddychao** [comment]
@jusporrer @SerenXia could you please let me know if you are happy with the features listed above for the next release? I am happy to fix the critical bugs you have met that may not be listed here. Thanks

**Comment by SerenXia** [comment]
For me these features sound good :)

**Comment by dominikbach** [comment]
Agreed; only it seems Issue #214 may not be needed for the current release?
