### ISSUE TITLE
create a new basis function for SCR data

### ISSUE THREAD

**Issue by thinkingg** [bachlab/PsPM#231]
### Feature Description
Hello: I want to use a customized basis function for analyzing SCR data. The shape of this function is (in Matlab):
%->> Y = [-0.00298752552641597	0.000167284731499435	0.000358725907948894	0.00205010171016065	0.00376719843298094	0.00520729948378901	0.00451857621904566	0.00212292524058506	0.000830059504259949	0.000829079204810332	-6.19398581505742e-05	-0.000874337420102439	-0.000572909074074961	0.000702989163687646	0.000866939220715425	-0.000149485060249731];
%->> plot(Y);
Time length is 16 seconds.
Would you like to help to write a Matlab script 'pspm_bf_costumized.m' to fit this shape. And I could implement this code into the PSPM package? 
Thank you so much.

**Comment by laurenyatlas** [comment]
Hi there - This post was actually a follow up to https://github.com/bachlab/PsPM/issues/148 We have our custom BF that Qingbao described above but would like to implement it in pspm_bf_FIR so that we can use it in our GLM. Is this the right approach?

**Comment by teddychao** [comment]
> Hi there - This post was actually a follow up to #148 We have our custom BF that Qingbao described above but would like to implement it in pspm_bf_FIR so that we can use it in our GLM. Is this the right approach?

Hi @laurenyatlas, 

Thank you for providing the updated information. We will have a look at this request based on the data and requested feature. May I know further details about why the current _pspm_bf_FIR_ cannot be used for the provided data?

Many thanks.

Best wishes,
Teddy

**Comment by thinkingg** [comment]
> > Hi there - This post was actually a follow up to #148 We have our custom BF that Qingbao described above but would like to implement it in pspm_bf_FIR so that we can use it in our GLM. Is this the right approach?
> 
> Hi @laurenyatlas,
> 
> Thank you for providing the updated information. We will have a look at this request based on the data and requested feature. May I know further details about why the current _pspm_bf_FIR_ cannot be used for the provided data?
> 
> Many thanks.
> 
> Best wishes,
> Teddy

Hi Ted: We do not want to use the canonical function coded in pspm_bf_scrf_f.m. We want to implement a customized function which shape is more fit to our data. Thank you. ---Qingbao Yu.

**Comment by dominikbach** [comment]
Hi Lauren
thanks very much, this makes sense. You don't need the FIR function for this - Ivan mentioned this just as an example.
You need to create a matlab function of the form 
[bs, x] = pspm_bf_customrf(td) 
where the input argument td is 1/sr (sr: sample rate), the output bs is the response function, sampled at the provided sample rate, and x is the time vector.
We are going to provide a generic function for this problem but it will take a few weeks. 
Hope this helps!
Best
Dominik

**Comment by thinkingg** [comment]
> Hi Lauren
> thanks very much, this makes sense. You don't need the FIR function for this - Ivan mentioned this just as an example.
> You need to create a matlab function of the form
> [bs, x] = pspm_bf_customrf(td)
> where the input argument td is 1/sr (sr: sample rate), the output bs is the response function, sampled at the provided sample rate, and x is the time vector.
> We are going to provide a generic function for this problem but it will take a few weeks.
> Hope this helps!
> Best
> Dominik

Hi Dom:
     Do you meant that we want to write our own matlab code 'pspm_bf_customrf.m' which would be similar to 'pspm_bf_scrf_f.m'? But in pspm_bf_scrf_f.m, there are also input parameters: p1, p2, p3, p4 in addition to td. the default values of those four parameters are [3.0745 0.7013 0.3176 0.0708]. How can we evaluate the values of p1, p2, p3, p4 for our customized RF? 
Thank you very much.
Qingbao Yu.
