### ISSUE TITLE
Implement trim in split_sessions

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#235]
The current _trim_ function has been implemented in _split_session_, but it seems that the _split echos_ section has not been updated. Not sure if it is encouraged to implement _trim_ for _split_echos_ too. If so, modifications are requested for _split echos_.

`startpoint = max(1, ceil(sta_p * srscr)); % convert from seconds into datapoints`
`stoppoint  = min(floor(sto_p * srscr), numel(datascr{1}.data));`
`epochs = dp_epochs(startpoint:stoppoint);`

**Comment by dominikbach** [comment]
Should be fixed by #252?
