### ISSUE TITLE
Data Display "Semi automatic mode" in Pre-processing of Heart data

### ISSUE THREAD

**Issue by Wjelena** [bachlab/PsPM#248]
### Summary
When preprocessing heart data with semi automatic mode "on", the data will sometimes not be properly displayed in the ecg editor, but instead in the PsPM GUI, or Batch.

### Expected Results
![ecg_editor](https://user-images.githubusercontent.com/47207904/122422221-459a2380-cf8d-11eb-92b0-327a9d3fc8ab.JPG)

### Actual Results
![batch_issue_ecg_editor](https://user-images.githubusercontent.com/47207904/122422240-492daa80-cf8d-11eb-84d4-b8ed4de4ddb7.JPG)
![batch_issue_ecg_semi](https://user-images.githubusercontent.com/47207904/122422264-4d59c800-cf8d-11eb-9b2a-8b4c95796f0c.JPG)

### Technical Info
* PsPM revision ID: 5.1.0 beta
* MATLAB version: 2018b

**Comment by teddychao** [comment]
@Wjelena Could you please send me the sample data so I can reproduce the error. Thanks.

**Comment by Wjelena** [comment]
hi Teddy

it's the DoxMem2 dataset that you also used for yanfang yesterday. Attached you can find a file to test it.

Best wishes
Jelena

--
Jelena Wehrli, MSc
Psychiatric University Hospital
***@***.***
bachlab.org
+41 44 384 26 60

-----"Teddy" ***@***.***> schrieb: -----
An: "bachlab/PsPM" ***@***.***>
Von: "Teddy" ***@***.***>
Datum: 17.06.2021 17:02
Kopie: "Wjelena" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [bachlab/PsPM] Data Display "Semi automatic mode" in Pre-processing of Heart data (#248)


 @Wjelena Could you please send me the sample data so I can reproduce the error. Thanks.

**Comment by teddychao** [comment]
Hi Jelena,

Thanks for the data. I am not sure which operation leads to this error. In general I guess it could be cause by the GUI. Could I know if you remember which operation leads to that issue? for example when you zoom in or zoom out the figure (I tried just now but I did not see error when I zoomed in or out).
I think the ECG editor GUI will be improved in the next release, so I will keep an eye on it.

Best wishes
teddy

**Comment by Wjelena** [comment]
Hi Teddy

Thank you for the reply! I tried a few more times and could not replicate it now, so I am not sure what I did before to cause this.
I will not use it in the course next week so it's not an urgent issue, I will let you know if I figure out what causes it.
Yanfang mentioned it might be because the figure is not specifically assigned so it might not be specified where it's plotted to.

Thanks for looking into this, have a nice evening!

Best wishes
Jelena--
Jelena Wehrli, MSc
Psychiatric University Hospital
***@***.***
bachlab.org
+41 44 384 26 60

-----"Teddy" ***@***.***> schrieb: -----
An: "bachlab/PsPM" ***@***.***>
Von: "Teddy" ***@***.***>
Datum: 17.06.2021 17:56
Kopie: "Wjelena" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [bachlab/PsPM] Data Display "Semi automatic mode" in Pre-processing of Heart data (#248)


 Hi Jelena,
 Thanks for the data. I am not sure which operation leads to this error. In general I guess it could be cause by the GUI. Could I know if you remember which operation leads to that issue? for example when you zoom in or zoom out the figure (I tried just now but I did not see error when I zoomed in or out).
 I think the ECG editor GUI will be improved in the next release, so I will keep an eye on it.
 Best wishes
 teddy
