### ISSUE TITLE
Trim for processing missing epochs

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#268]
### Summary
_Trim_ assumes that the data to be processed contains sufficient information, shown as dominating non zero values. Values of start and end points for trimming are generated through combining both the original data and the _reference_. This logic makes it not applicable for processing missing epochs, because missing epochs contains only 0 and 1. Therefore, _trim_ needs to be updated for being applicable for missing epochs.

**Comment by teddychao** [comment]
@dominikbach I have an idea in my mind. I will pull a request for this issue. May I ask you to have a look there. Many thanks.

**Comment by dominikbach** [comment]
@teddychao since I wrote the update to split_sessions, I'll have a quick go at it, I think it can be simplified.

**Comment by dominikbach** [comment]
@teddychao

pspm_split_sessions combines the marker data with the missing data channel and then calls pspm_trim. There is no issue there, unless you disable the marker channel. So I think this issue can be closed.
