### ISSUE TITLE
Default settings for pspm_scr_pp

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#273]
### Feature Description

Users mentioned failures of using pspm_scr_pp. The reason is potentially the incompatibility between the default parameters and the imported data. Is it ok to set some default parameters dynamic based on the data? It would be easier for users and prevent all NaN output.

**Comment by teddychao** [comment]
@dominikbach Can we discuss about this please, thanks.

**Comment by dominikbach** [comment]
Could you send an example?

**Comment by teddychao** [comment]
> Could you send an example?

Hi Dom, thanks for the comment, please find the example data [here](https://liveuclac-my.sharepoint.com/:u:/g/personal/skgtdz0_ucl_ac_uk/EbIc2KfAfvlLpyGz6zWtresB_XW3JwmXy0NNPcZeTOU2yQ?e=mdrO4m), thanks 🙂
Best wishes
Ted
