### ISSUE TITLE
Integrate pspm_find_valid_fixations with pspm_pupil_pp

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#275]
### Feature Description

pspm_find_valid_fixations should allow:
- taking a preprocessed pupil channel as input
- allow a r/l-comined preprocessed pupil channel
- in this case, integrate r/l gaze channels with nanmean

**Comment by SerenXia** [comment]
Hi @teddychao I created a new branch "eye-data-pp" for this issue.

I have documented some new gaze channels (preprocessed, combined, or combined preprocessed) into pspm_init.

Additionally, the branch should deal with the following features for gaze data:
1. gaze data preprocessing
similar to pupil preprocessing; needs gaze channel options such as, use the left eye, the right eye, the best eye, or combine two eyes and use the combined gaze data channel

2. find valid fixation function
should then use the corresponding gaze channels

3. in the other involved functions, e.g. model inversion
these functions should take the preprocessed combined / preprocessed / combined / raw data channels as input data when doing model inversion. I think it is probably already implemented in pspm_load_data or somewhere, not 100% sure

**Comment by teddychao** [comment]
> Hi @teddychao I created a new branch "eye-data-pp" for this issue.
> 
> I have documented some new gaze channels (preprocessed, combined, or combined preprocessed) into pspm_init.
> 
> Additionally, the branch should deal with the following features for gaze data:
> 
> 1. gaze data preprocessing
>    similar to pupil preprocessing; needs gaze channel options such as, use the left eye, the right eye, the best eye, or combine two eyes and use the combined gaze data channel
> 2. find valid fixation function
>    should then use the corresponding gaze channels
> 3. in the other involved functions, e.g. model inversion
>    these functions should take the preprocessed combined / preprocessed / combined / raw data channels as input data when doing model inversion. I think it is probably already implemented in pspm_load_data or somewhere, not 100% sure

Hi Yanfang, 

Thank you for creating the modifications in this issue. Could I know how you would like me to implement your modifications? I am not able to see your modifications if you do not prefer to publish them in a new pull request. If you have not do any modifications but would like me to follow your suggestions above, there will be no need to create a branch then.

Thanks.

Best wishes
Teddy

**Comment by SerenXia** [comment]
> > Hi @teddychao I created a new branch "eye-data-pp" for this issue.
> > I have documented some new gaze channels (preprocessed, combined, or combined preprocessed) into pspm_init.
> > Additionally, the branch should deal with the following features for gaze data:
> > 
> > 1. gaze data preprocessing
> >    similar to pupil preprocessing; needs gaze channel options such as, use the left eye, the right eye, the best eye, or combine two eyes and use the combined gaze data channel
> > 2. find valid fixation function
> >    should then use the corresponding gaze channels
> > 3. in the other involved functions, e.g. model inversion
> >    these functions should take the preprocessed combined / preprocessed / combined / raw data channels as input data when doing model inversion. I think it is probably already implemented in pspm_load_data or somewhere, not 100% sure
> 
> Hi Yanfang,
> 
> Thank you for creating the modifications in this issue. Could I know how you would like me to implement your modifications? I am not able to see your modifications if you do not prefer to publish them in a new pull request. If you have not do any modifications but would like me to follow your suggestions above, there is unlikely need to create a branch then.
> 
> Thanks.
> 
> Best wishes
> Teddy

Hi Teddy, sorry I did not realise that you cannot see my changes. I am gonna open a new pull request for it, so you can modify that branch as well.
