### ISSUE TITLE
Hotfix 5.1.1 checklist 

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#278]
### Summary
This is a discussion page of the issues that have been fixed and are to be fixed in version 5.1.1.
Please feel free to drop messages about the issues to be fixed but not mentioned in your opinion.

#### pspm_dcm
Missing epochs were not processed properly due to messy channel and data array referring #266 
Empty epochs not sorted in _pspm_dcm_ #280 
#### pspm_scr_pp
GUI unexpectedly throw warnings #255 
#### pspm_split_sessions
GUI issue that leads to software crash #262 
GUI accepts too many data files and missing epochs #269 
Missing epochs were not processed successfully #272 
#### miscellaneous
Welcome texts have not been updated #260 
Display issue for some GUI windows #259 #264 #265

**Comment by dominikbach** [comment]
I think #255 has solved itself - we haven't done anything?(i. e. Not for release notes).

**Comment by dominikbach** [comment]
Otherwise, all good.

**Comment by dominikbach** [comment]
Juliana flagged a new issue in DCM - I'm working on the solution and it should be included in the hotfix as well.

**Comment by SerenXia** [comment]
I have reopened issue #213 
but I am not sure if this should be fixed in the hotfix

**Comment by teddychao** [comment]
> I have reopened issue #213
> but I am not sure if this should be fixed in the hotfix

Thanks Yanfang. I do not remember I have corrected that issue. I am currently doing #275 , but please feel free to let me know if #213 is urgent. Thanks.

**Comment by teddychao** [comment]
> I think #255 has solved itself - we haven't done anything?(i. e. Not for release notes).

Sorry I am a little confused.. I remember I did update some code in cfg, because it was not just the issue of missing `job` in `()`.

**Comment by dominikbach** [comment]
Yes, you are right; you made a bugfix.
(I mixed it up with #273 which you had not mentioned of course).
So all good.
