### ISSUE TITLE
Test function for pspm_bf_data

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#284]
### Feature Description
_pspm_bf_data_ is a newly implemented function that provides a generic interface for creating a user-defined response function from a data vector saved in a *.mat file.
A test function is required for maintaining this function.

**Comment by teddychao** [comment]
@dominikbach Could I know if you would mind me doing this by updating the general test function *pspm_bf_test*? Thanks

**Comment by dominikbach** [comment]
Sure, this sounds good. 

Dominik Bach
