### ISSUE TITLE
pspm find marker events: flank setting

### ISSUE THREAD

**Issue by SerenXia** [bachlab/PsPM#308]
### Summary
optional field "flank" for marker events is only set available in pspm_get_marker.m and pspm_get_event.m, but not in pspm_import.m

When we import datafiles into pspm, we call function "pspm_import" to go through all data type and preprocess markers.
In pspm_import, line 201, depending on data type, specific function will be called. 

So for markers, function "pspm_get_marker" will be called, with "import" as input argument. 

In this function, function "pspm_get_events" will be then called, again with "import" as input argument.

In "pspm_get_events" and "pspm_get_marker", structure "import" contains an optional field "flank" to determine the orientation of marker calculation (see get events function). However, this was not available in pspm_import, meaning, although flank option was set, users actually have no way to use it.

### Technical Info
* PsPM revision ID: 5.1.1
* MATLAB version: 2018b

**Comment by dominikbach** [comment]
Thanks for raising this issue.

To understand, when a user sets import{k}.flank in a command-line call to pspm_import, then the field 'flank' is passed on to pspm_get_events, correct?

Whereas, it does not come through when used via GUI?

**Comment by SerenXia** [comment]
> Thanks for raising this issue.
> 
> To understand, when a user sets import{k}.flank in a command-line call to pspm_import, then the field 'flank' is passed on to pspm_get_events, correct?
> 
> Whereas, it does not come through when used via GUI?

Exactly.
Also in pspm_import, in the help text, 'flank' was not set. Neither set in the codes. And not via GUI, too.

**Comment by teddychao** [comment]
I checked `pspm_get_marker.m`, and I found `.flank` was mentioned in descriptions but not used in the code. I think it needs work too.

**Comment by teddychao** [comment]
Hi, I think `flank` was defined in some situations.. an example is shown here.
<img width="876" alt="image" src="https://user-images.githubusercontent.com/3895146/152791407-bb6589f8-66cb-4ae3-989a-ef9bf5f0ecbb.png">
I checked the code and found flank will be provided for events. I am not sure which import data would need specifying `flank`. We may need some discussion about this on today's meeting.
