### ISSUE TITLE
Implement tests for frequently used PsPM functions

### ISSUE THREAD

**Issue by eozd** [bachlab/PsPM#37]
### Summary
Below functions implement some core functionality, but currently are not tested. We need to implement tests for them.

- [x] `pspm_hb2hp.m`
- [x] `pspm_filtfilt.m`
- [x] `pspm_butter.m`

**Comment by irojkov-ph** [comment]
Should I also modify the Developer Guide ?

**Comment by eozd** [comment]
Yes, please. We are all set for the new release, so we should prepare the manual and developer guide as the first step.
