### ISSUE TITLE
Management of "master" branch

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#417]
### Summary

Master branch is not maintained.

### Expected Results

Master branch corresponds to latest release, to allow using latest release via git without having to specify it explicitly.

### Actual Results

Master branch is stuck in a previous version.

### (Optional) Possible Cause and Solutions

Merge develop into master with every release.

**Comment by teddychao** [comment]
Error message
<img width="641" alt="Screenshot 2022-12-04 at 04 03 19" src="https://user-images.githubusercontent.com/3895146/205473848-dd6af9fe-5b36-48a9-aab7-805e2b2b329b.png">
