### ISSUE TITLE
PsPM loads, but does not run from script

### ISSUE THREAD

**Issue by ahulsman** [bachlab/PsPM#436]
### Summary

Dear Dominik,

I seem to have an issue when I try to run my PsPM scripts from code (within the batch, everything works fine). When I run my script from code, PsPM is loaded (i.e. I get this notification: PsPM: loading defaults ... ). But then nothing else happens. 

This is a part of my code:

`
addpath('/home/affneu/annhuls/PsPM_v6/');
addpath('/project/3023001.03/FA_fMRI/Scripts/SCR');
physdata_dir = '/project/3023001.03/FA_fMRI/Data/Physiology/Raw';
pspm_dir = '/project/3023001.03/FA_fMRI/Data/Physiology/PsPM';
processing = [4];
subjects = 5
for subj = subjects 
    if subj<10
        sub = ['sub' '00' num2str(subj)];
    elseif subj>9&subj<100 
        sub = ['sub' '0' num2str(subj)];
    else
        sub = ['sub' num2str(subj)];
    end
    disp(['Starting on: ' sub ''])

    if find(processing==4) > 0 % if processing = 4, run model

        datafilename = (['pspm_', num2str(sub),'.mat']); 
        datafile = fullfile(pspm_dir, "Data", datafilename); 

        timingfilename = (['timing_' num2str(sub), '.mat']);
        timingfile = fullfile(pspm_dir, "Timing", timingfilename);

        conditionsfilename = (['conditions_' num2str(sub), '.mat']);
        conditionsfile = fullfile(pspm_dir, "Conditions", conditionsfilename);
        load(conditionsfile);

        LRLT = cell2mat(conditions(1,1));
        LRMT = cell2mat(conditions(1,2));
        LRHT =cell2mat(conditions(1,3));
        MRLT = cell2mat(conditions(1,4));
        MRMT =cell2mat(conditions(1,5));
        MRHT =cell2mat(conditions(1,6));
        HRLT = cell2mat(conditions(1,7));
        HRMT = cell2mat(conditions(1,8));
        HRHT = cell2mat(conditions(1,9));
        
        outputname = (['1stlevel_', num2str(sub)]);
        outputdir = fullfile(pspm_dir, "Output");
        
        FA_fMRI_SCR_1stlevel
`

FA_fMRI_SCR_1stlevel:

`
nrun = 1; % enter the number of runs here
jobfile = {'/project/3023001.03/FA_fMRI/Scripts/SCR/FA_fMRI_SCR_1stlevel_job.m'};
jobs = repmat(jobfile, 1, nrun);
inputs = cell(13, nrun);
for crun = 1:nrun
    inputs{1, crun} =  outputname; % Non-Linear Model: Model Filename - cfg_entry
    inputs{2, crun} = cellstr(outputdir); % Non-Linear Model: Output Directory - cfg_files
    inputs{3, crun} = cellstr(datafile); % Non-Linear Model: Data File - cfg_files
    inputs{4, crun} = cellstr(timingfile); % Non-Linear Model: Design - cfg_choice
    inputs{5, crun} = LRLT; % Non-Linear Model: Index - cfg_entry
    inputs{6, crun} = LRMT; % Non-Linear Model: Index - cfg_entry
    inputs{7, crun} = LRHT; % Non-Linear Model: Index - cfg_entry
    inputs{8, crun} = MRLT; % Non-Linear Model: Index - cfg_entry
    inputs{9, crun} = MRMT; % Non-Linear Model: Index - cfg_entry
    inputs{10, crun} = MRHT; % Non-Linear Model: Index - cfg_entry
    inputs{11, crun} = HRLT; % Non-Linear Model: Index - cfg_entry
    inputs{12, crun} = HRMT; % Non-Linear Model: Index - cfg_entry
    inputs{13, crun} = HRHT; % Non-Linear Model: Index - cfg_entry
end
job_id = cfg_util('initjob', jobs);
sts    = cfg_util('filljob', job_id, inputs{:});
if sts
    cfg_util('run', job_id);
end
cfg_util('deljob', job_id);
`

Job file:
`
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.modelfile = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.outdir = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.chan.chan_def = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.datafile = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.timing = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(1).name = 'LRLT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(1).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(2).name = 'LRMT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(2).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(3).name = 'LRHT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(3).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(4).name = 'MRLT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(4).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(5).name = 'MRMT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(5).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(6).name = 'MRHT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(6).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(7).name = 'HRLT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(7).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(8).name = 'HRMT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(8).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(9).name = 'HRHT';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.condition(9).index = '<UNDEFINED>';
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.session.missing.no_epochs = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.data_options.norm = 1;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.data_options.filter.def = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.data_options.substhresh = 2;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.data_options.lasttrialcutoff = 7;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.data_options.constr_model = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.resp_options.crfupdate = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.resp_options.indrf = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.resp_options.getrf = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.resp_options.rf = 0;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.inv_options.depth = 2;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.inv_options.sfpre = 2;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.inv_options.sfpost = 5;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.inv_options.sffreq = 0.5;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.inv_options.sclpre = 2;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.inv_options.sclpost = 5;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.inv_options.ascr_sigma_offset = 0.1;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.disp_options.dispwin = 1;
matlabbatch{1}.pspm{1}.first_level{1}.scr{1}.dcm.disp_options.dispsmallwin = 0;
`

Workspace:
![image](https://user-images.githubusercontent.com/66479138/206173655-58b1f48c-de8b-48fa-8b5f-cdb3242779a8.png)

Do you know what could be the issue here? 

Kind regards,

Anneloes

### Technical Info
* PsPM revision ID: 6
* MATLAB version: 2021b

**Comment by teddychao** [comment]
Hi @ahulsman, thanks for proposing the issue.
To allow us better investigate the issue, could you please save the current workspace by using the command `save issue_workspace.mat` and sent it together with the source files to [us](dadi.zhao@outlook.com) so that we can replicate the issue and find the solution for you?
Many thanks.
Best wishes
Teddy

**Comment by ahulsman** [comment]
Dear Teddy, 

Thank you for your quick reply. Here are the files that you requested. 
[4BachLab.zip](https://github.com/bachlab/PsPM/files/10183498/4BachLab.zip)

Best,

Anneloes

**Comment by teddychao** [comment]
Hi @ahulsman 
Thanks for the uploaded files and it is really helpful. I am able to rerun the code but it seems like I have got errors instead of seeing nothing in the console. The error I got was from the cfg_util and I am unsure that is caused by the job definition. I checked the reported issue description and I noticed there was no error when the job was run within the batch. May I know if that means there was no issue when it was run with the section _batch_ in the GUI?
Best wishes
Teddy

**Comment by ahulsman** [comment]
Hi @teddychao,

When I manually fill in all the fields in the batch, it runs perfectly. 
When I script it, it does not run at all. If I have the PsPM GUI opened and then run it from script, I don't get the cfg_util error. When I don't have the PsPM GUI opened on the side, it does give me the cfg_util error as well.


Best,

Anneloes

**Comment by ahulsman** [comment]
Hi @teddychao ,

I tried creating a new script + job file for my first level analysis and so far things seem to work :) I filled out the exact same things as in my previous script + job file, so I have no idea why it's working now and not before... Anyway, I'm glad things seem to be working out.


Best,

Anneloes

**Comment by teddychao** [comment]
Hi @ahulsman 

Great news, hope it is working for other cases as well.
I will mark this issue as resolved at the moment. If the issue happens again, please feel free to reopen this issue.
Thanks.

Best wishes
teddy
