### ISSUE TITLE
Fail to import pupil size data (.asc)

### ISSUE THREAD

**Issue by kirkzmr** [bachlab/PsPM#459]
Summary

I failed to import the data converted from .edf file using data viewer. The setting in pspm was: data column type = marker; eyetracker distance = -1; distance unit = mm. When running pspm, matlab gave the following error messages:

------------------------------------------------------------------------
06-Feb-2023 15:38:31 - Running 'Import'
06-Feb-2023 15:38:32 - Failed  'Import'
Error using datetime
Unable to convert ' Tue May 24 07:35:49 2022' to datetime using the format 'eee MMM d HH:mm:ss yyyy'. If the date/time text contains day, month, or time zone names in a language foreign to the 'zh_CN' locale, those might not be recognized. You can specify a different locale using the 'Locale' parameter.
In file "C:\Program Files\MATLAB\R2022b\toolbox\matlab\datatypes\datetime\@datetime\datetime.m" (???), function "datetime.datetime" at line 658.
In file "C:\Program Files\MATLAB\R2022b\PsPM_v6.0\Import\eyelink\import_eyelink.m" (???), function "parse_metadata" at line 189.
In file "C:\Program Files\MATLAB\R2022b\PsPM_v6.0\Import\eyelink\import_eyelink.m" (???), function "parse_eyelink_file" at line 128.
In file "C:\Program Files\MATLAB\R2022b\PsPM_v6.0\Import\eyelink\import_eyelink.m" (???), function "import_eyelink" at line 46.
In file "C:\Program Files\MATLAB\R2022b\PsPM_v6.0\pspm_get_eyelink.m" (???), function "pspm_get_eyelink" at line 58.
In file "C:\Program Files\MATLAB\R2022b\PsPM_v6.0\pspm_import.m" (???), function "pspm_import" at line 224.
In file "C:\Program Files\MATLAB\R2022b\PsPM_v6.0\pspm_cfg\pspm_cfg_run_import.m" (???), function "pspm_cfg_run_import" at line 117.

The following modules did not run:
Failed: Import
If the problem can be fixed without modifying the job, the computation can be resumed by running
   cfg_util('cont',1)
from the MATLAB command line.
 

Technical Info
* PsPM version: 6.0.0
* MATLAB version: R2022b

**Comment by teddychao** [comment]
Hi,
Thanks for posting the issue here.
Could you please upload the sample data which leads to the error described above so that we can replicate and investigate the issue?
Best wishes
Teddy

**Comment by teddychao** [comment]
Hi @kirkzmr 
Thank you for the new updates for the issue.
Another user has proposed a similar issue to this problem and perhaps they are caused by the same bug/mistake in the code. Since we are now able to get the sample file, perhaps the most efficient way is I can investigate it first and let you know the solution so you can test whether your issue can be solved at the same time.
Sounds ok?
Thanks.
Best wishes
Teddy
