### ISSUE TITLE
Eyelink (.asc) import issue

### ISSUE THREAD

**Issue by ravidasucl** [bachlab/PsPM#465]
### Summary
Hi Teddy,

I am encountering a similar issue to a previous poster, in that attempted import of pupil data into PsPM 6 from and Eyelink file (converted to .asc) throws an error regarding an index not being specified in 'outfile'. Perhaps I am missing something obvious, but I have been unable to find information in the manual or previous discussions that resolve this issue. I give the code that produces the error, below, the error itself and can send the example file to which it pertains so you can replicate it if you need.

**import.m code:**

#459 matlabbatch{1}.pspm{1}.prep{1}.import.datatype.eyelink.datafile = {'<FILEPATH>\006AQS1.asc'};
matlabbatch{1}.pspm{1}.prep{1}.import.datatype.eyelink.importtype{1}.marker.chan_nr.chan_nr_def = 0;
matlabbatch{1}.pspm{1}.prep{1}.import.datatype.eyelink.importtype{1}.marker.flank_option = 'default';
matlabbatch{1}.pspm{1}.prep{1}.import.datatype.eyelink.importtype{2}.pupil_l.chan_nr.chan_nr_spec = 4;
matlabbatch{1}.pspm{1}.prep{1}.import.datatype.eyelink.eyelink_trackdist = -1;
matlabbatch{1}.pspm{1}.prep{1}.import.datatype.eyelink.distance_unit = 'mm';
matlabbatch{1}.pspm{1}.prep{1}.import.overwrite = false;

**The error itself:** (I have redacted the actual filepath)
------------------------------------------------------------------------
09-Feb-2023 12:27:42 - Running job #2
------------------------------------------------------------------------
09-Feb-2023 12:27:42 - Running 'Import'
09-Feb-2023 12:27:45 - Failed  'Import'
Output argument "index" (and maybe others) not assigned during call to "bsearch".
In file "C:\<FILEPATH>PsPM_v6.0.0\Import\eyelink\import_eyelink.m" (???), function "parse_messages" at line 281.
In file "C:\<FILEPATH>\PsPM_v6.0.0\Import\eyelink\import_eyelink.m" (???), function "import_eyelink" at line 49.
In file "C:\<FILEPATH>\PsPM_v6.0.0\pspm_get_eyelink.m" (???), function "pspm_get_eyelink" at line 58.
In file "C:\<FILEPATH>\PsPM_v6.0.0\pspm_import.m" (???), function "pspm_import" at line 224.
In file "C:\<FILEPATH>\PsPM_v6.0.0\pspm_cfg\pspm_cfg_run_import.m" (???), function "pspm_cfg_run_import" at line 117.

The following modules did not run:
Failed: Import
If the problem can be fixed without modifying the job, the computation can be resumed by running
   cfg_util('cont',2)
from the MATLAB command line.

Many thanks in advance for any help you are able to offer!

Ravi

### Technical Info
* PsPM revision ID: 6.0.0
* MATLAB version: R2019b

**Comment by teddychao** [comment]
Hi Ravi,
Many thanks for proposing the issue and the error information provided above.
Could you please send the sample file or the corresponding sharing link to me by email: skgtdz0@ucl.ac.uk and it will really help since I can then replicate the error and therefore investigate the issue.
Thank you.
Best wishes 
Teddy

**Comment by timok91** [comment]
Hi @teddychao ,

I got the same error message as Ravi. May I also send you a sample file by email? Or is there already a solution for this error?

Best wishes
Timo

**Comment by ravidasucl** [comment]
Hi @timok91 ,

I believe this was caused by a compatibility issue with the newer .asc converter used by the Eyelink/Dataviewer. Teddy and the team have since updated PsPM which should fix the issue. 

Best wishes,

Ravi

**Comment by dominikbach** [comment]
Fixed.

**Comment by amjh23** [comment]
Dear experts,
I am doing my first pspm analysis and have similar problems, so am posting this here with this thread:
I managed to import pupil data collected with eyelink 1000 plus in the older version of pspm (v5.1.1) but have not managed to import them in current version of pspm (v6.1.0).

I tried the following two ways to transform my EDF data to ASC format, following this description:
https://www.sr-research.com/support/thread-7674.html

1) VisualEDF2ASC provided with latest version of DataViewer (4.3.210): Import finishes without errors in pspm 6.1.0 but does not produce an imported file. Import creates an error message in pspm 5.1.1.

2) Command line EDF2ASC provided with the lastest version of the EyeLink Developers Kit / API (v2.1.762): Import finishes without error in pspm 6.1.0 but does not create an imported file. Import works without problems in pspm 5.1.1.

As I would prefer to use the latest version of pspm, I wanted to ask if you have a solution?

Many thanks,
am

**Comment by amjh23** [comment]
P.S. Related to my above question: Would it be possible to use pspm 5.1.1 to import the data and then use pspm 6.1.0 for preprocessing and analysis of those data? Or is that in geneal not a good idea?

Best,
am

**Comment by teddychao** [comment]
> Dear experts, I am doing my first pspm analysis and have similar problems, so am posting this here with this thread: I managed to import pupil data collected with eyelink 1000 plus in the older version of pspm (v5.1.1) but have not managed to import them in current version of pspm (v6.1.0).
> 
> I tried the following two ways to transform my EDF data to ASC format, following this description: https://www.sr-research.com/support/thread-7674.html
> 
> 1. VisualEDF2ASC provided with latest version of DataViewer (4.3.210): Import finishes without errors in pspm 6.1.0 but does not produce an imported file. Import creates an error message in pspm 5.1.1.
> 2. Command line EDF2ASC provided with the lastest version of the EyeLink Developers Kit / API (v2.1.762): Import finishes without error in pspm 6.1.0 but does not create an imported file. Import works without problems in pspm 5.1.1.
> 
> As I would prefer to use the latest version of pspm, I wanted to ask if you have a solution?
> 
> Many thanks, am

Dear Am,

Thank you for posting the issue here.
May we have some sample data that can replicate this issue so that we can investigate it?
If the data cannot be sent to public domain, maybe consider sending to my email address: skgtdz0@ucl.ac.uk.
Look forward to your replies.
Best wishes
teddy

**Comment by amjh23** [comment]
Dear teddy,

Many thanks for your help. I have sent you an email with the data.

Best,
am

**Comment by amjh23** [comment]
Hi Teddy,

I sent the original email on Monday and have re-sent it just now, 
Because my sample data is too big to send by email, I instead included a link to a file share server in the email.

Please let me know in case the second email did not arrive either.

Best,
am

**Comment by amjh23** [comment]
Dear Teddy,
A colleague just told me the solution to my problem with pspm 6.1.0 import: In the import batch script, the "overwrite existing file" option has to be set to "yes", otherwise no imported file will be created, even if there is no existing pspm_ file in the current folder. 

Best,
am

**Comment by dominikbach** [comment]
This issue has been fixed.
