### ISSUE TITLE
Duration setting in "Data and Design"

### ISSUE THREAD

**Issue by kirkzmr** [bachlab/PsPM#494]
### Summary
Dear Teddy,

I have a question on the "Data and Design" part in first-level GLM. In this section, the "Design" provides the option "Enter conditions manually" and we shall vector of durations of each event for this condition. PsPM set 0 as default. 

The duration of CS in my experiment is 4 seconds. Each CS has same duration. Shall I change the duration from 0 to 4? 
Actually I have done the GLM for PS (fear-conditioning) treating duration as 0 and 4. I found two results were different. May I ask why such difference happens and which one should be appropriate?

Thank you for your time so much.

### Technical Info
* PsPM revision ID: v6.0.0
* MATLAB version: R2022b

**Comment by dominikbach** [comment]
Hi kirkzmr

all models in PsPM have been designed and tested for a duration of "0". The "duration" field is a legacy from fMRI and is experimental - I wouldn't advise using it.

Specifically, all responses we model in PsPM are phasic - short neural firing in response to some event. There are no published & validated PsPM models for tonic neural firing (e.g. tonic heart rate changes etc.).

For PS-FC - use "0" duration.

Hope this helps.
Dominik
