### ISSUE TITLE
Estimating inputs to the pupil model

### ISSUE THREAD

**Issue by fmelinscak** [bachlab/PsPM#50]
### Feature Description

I'm relaying a feature request from @dominikbach: the feature in question is estimating inputs of the pupil response model.
The idea is to enable analyses similar to ones from the [Korn & Bach (2016) paper](https://www.doi.org/10.1167/16.3.28) (in particular, analyses leading to figures 9, 10, 11).

The assumption here is that the pupil can be modeled as an LTI system, with the exact response function depending on whether pupil dilations or constrictions are modeled (this is implemented in PsPM functions `pspm_bf_ldrf_gm.m` and `pspm_bf_lcrf_gm.m` respectively).
Additionally, the method assumes the functional form of the input signal (in the paper, this is a gamma pdf), and the parameters of this input function are optimized such that the squared error between the prediction (convolution of the input and the LTI response function) and the observed data is minimized.
The paper doesn't explicitly mention which optimization method was used, but I think it might have been `fminsearch` (other analyses in the paper use this method).

The function should have a similar API as `pspm_glm`, and it should support condition-wise model fitting.
Importantly (and differently from the GLM), all the responses of a condition should be averaged before the input is estimated.

To start work on this, you would need some pupil size data with trial-wise markers.
I believe Dominik will get in touch with Christoph about getting the data from the paper, but in the meantime, you can use any pupil size data that has markers.

**Comment by eozd** [comment]
It seems that this new function shares many of the required functionalities with `pspm_glm`. Do we want some sort of refactoring of `pspm_glm` before starting the implementation?

**Comment by fmelinscak** [comment]
As a user, I don't have a strong opinion either way. But I think it would be ok to refactor `pspm_glm` only if there are comprehensive tests in place (and, in particular, regression tests with some actual data), to ensure that results of `pspm_glm` don't change due to refactoring, since it's a workhorse of PsPM-based analysis pipelines.
