### ISSUE TITLE
Unable to convert ECG data to Heart Rate Period

### ISSUE THREAD

**Issue by dc307** [bachlab/PsPM#508]
### Steps to Reproduce
1. Import ECG data
2. Select Preprocess heart data
3. Choose Convert ECT to Heart Period and fill in appropriate fields

### Expected Results

In 5.11 this would add a channel of heart rate period

### Actual Results

Error:

Undefined function 'pspm_ecg2hb' for input arguments of type 'struct'.
In file "/MATLAB/PsPM_v6.0.0/pspm_cfg/pspm_cfg_run_pp_heart_data.m" (v746), function "pspm_cfg_run_pp_heart_data" at line 80.

The following modules did not run:
Failed: Preprocess heart data
If the problem can be fixed without modifying the job, the computation can be resumed by running
   cfg_util('cont',1)
from the MATLAB command line.

### (Optional) Possible Cause and Solutions

pspm_ecg2hb is missing from 6.0.0. It is not on the repository. 

### Technical Info
* PsPM version: 6.0
* MATLAB version: 2023a

**Comment by teddychao** [comment]
Hi @dc307 
Thanks for posting the issue.
This is a new bug introduced by our recent code sorting for the A2B functions. In the src folder of Version 6.0 you can see a series of pspm_convert_... functions. We did not manage to update the UI for these files, but the function itself isn't deleted. We will fix this issue in Version 6.1. You may also consider downloading the develop branch after we fix this issue.
Thank you again for posting this issue.
Best wishes
Teddy

**Comment by dominikbach** [comment]
Solution:
change line 52 in pspm_cfg_run_pp_heart_data from ```[sts, winfo] = pspm_ecg2hb(fn, chan, opt);```  to ```[sts, winfo] = pspm_convert_ecg2hb(fn, chan, opt);``` and similarly in line 80

**Comment by teddychao** [comment]
Hi @dc307 
We have fixed this issue and the issue of Batch Editor in the develop branch.
Please feel free to download the latest develop branch code to see the issue fixed, or you can also wait for our next release in the upcoming weeks.
I will close this pull request since it has been fixed. If there are further questions, please feel free to contact me.
Best wishes
Teddy
