### ISSUE TITLE
Streamline function output

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#519]
### Feature Description
- make a decision on static vs dynamic output
Suggestion for static output: 
- sts should be provided for all internally called functions that produce output, to offer a systematic way to handle problems without interrupting batch processing
- functions that are called like scripts for their side effect don't need sts

**Comment by teddychao** [comment]
I agree with the concept that "sts should be provided for all internally called functions that produce output, to offer a systematic way to handle problems without interrupting batch processing".
The reason why I conceptualise "dynamic output" is to minimise the modifications of how these functions are called.
If we change all functions to `[ sts, Y ] = function [ X ]` it will be a heavy update.
For example `glm = pspm_glm [ X ]` will need to be updated into `[sts, glm] = pspm_glm [ X ]`. As the result, all the functions which call `pspm_glm` will need to by changed.
