### ISSUE TITLE
Older-version MATLAB poorly supports AppDesigner

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#523]
### Feature Description
MATLAB has recommended us to develop apps by using its newly introduced AppDesigner, but it failed to explain potential issues when users use AppDesigner with older version of MATLAB. I tested the AppDesigner version of PsPM with open data on MATLAB 2019a and get warnings like 

> PsPM: loading defaults ... Error using matlab.ui.Figure/set
Functionality not supported with figures created with the uifigure function. For more information, see Graphics Support in App Designer.
Error in cfg_ui>local_pointer (line 189)set(get(0,'Children'),'Pointer',ptr);
Error in cfg_ui>MenuFileRun_Callback (line 702)
local_pointer('watch');
Error in gui_mainfcn (line 95)        feval(varargin{:});
Error in cfg_ui (line 53)
    gui_mainfcn(gui_State, varargin{:}); 
Error while evaluating PushTool ClickedCallback.

This issue only appears in MATLAB 2019a (Windows) and does not appear on MATLAB 2022a (Windows) or MATLAB 2023a (macOS, Intel). This may be something that needs to be explained to users when they use older versions of MATLAB.

**Comment by dominikbach** [comment]
resolved.
