### ISSUE TITLE
Check channel replacing behaviour

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#533]
### Summary
Users have reported that PsPM does not replace channel when users have set `channel_actions` as replace over `add`. Relevant functions may include (but may not only limit to) `pspm_convert_pixel2unit`, `pspm_convert_gaze_distance` and `pspm_pupil_pp`. It is necessary to check the reason and avoid this issue for any other functions which have this feature.

**Comment by dominikbach** [comment]
User reported that channel is added when the units are changed and no channel with new units exist. This should be the desired behaviour. Could you confirm @teddychao?

**Comment by teddychao** [comment]
> User reported that channel is added when the units are changed and no channel with new units exist. This should be the desired behaviour. Could you confirm @teddychao?

Hi @dominikbach Apologies. This is the question proposed by Marina. I saw on Slack it seems to be a misunderstanding for her and the current behaviour is expected. Shall I close this issue, if my understanding is correct now?
