### ISSUE TITLE
scr_pp does not detect artefacts in SCR channel

### ISSUE THREAD

**Issue by SerenXia** [bachlab/PsPM#548]
### Summary
This automatic preprocessing function works perfectly for most of the data files, except for one file with an artefact period. 
### Steps to Reproduce
options = struct();
options.max = 100;
options.missing_epochs_filename = "output filename";
[sts, out] = pspm_scr_pp("data file", options);

### Expected Results
get an output file with variable "epochs" which contains the start and end time of the artefact
### Actual Results
the output epoch is empty
### (Optional) Possible Cause and Solutions
it looks like that the default "absolute SCR values in microSiemens" and "slope per second" criteria cannot detect artefacts with a sudden increase (like, 90 degree increase in data) and decrease. see the example data (attached).

### Technical Info
* PsPM version: 6.0.0
* MATLAB version: 9.13.0.2049777 (R2022b)
[tpspm_REW2_acq_0005_sn02.zip](https://github.com/bachlab/PsPM/files/13044107/tpspm_REW2_acq_0005_sn02.zip)

**Comment by teddychao** [comment]
Hi @SerenXia 
Thanks for posting the issue.
May I ask if you have ever tried PsPM version 6.1.0?
Best wishes
Teddy

**Comment by SerenXia** [comment]
> Hi @SerenXia Thanks for posting the issue. May I ask if you have ever tried PsPM version 6.1.0? Best wishes Teddy

do you update pspm_scr_pp.m in v6.1.0?

**Comment by teddychao** [comment]
> > Hi @SerenXia Thanks for posting the issue. May I ask if you have ever tried PsPM version 6.1.0? Best wishes Teddy
> 
> did you update pspm_scr_pp.m in v6.1.0? I did not find any update information about this in the 6.1.0 release.

Hi @SerenXia 

Apologies, perhaps the issue remains in version 6.1.
For avoiding misunderstanding of the issue, would you mind sending me a dataset that works well with `scr_pp` for comparison purpose?
Thank you.

Best wishes
Teddy

**Comment by teddychao** [comment]
Hi @SerenXia 

May I ask if this is what you expect to see?
<img width="672" alt="image" src="https://github.com/bachlab/PsPM/assets/3895146/f65781ad-0006-495e-8d17-3aec9fe8f0b5">
Thanks.

Best wishes
Teddy

**Comment by SerenXia** [comment]
> Hi @SerenXia
> 
> May I ask if this is what you expect to see? <img alt="image" width="672" src="https://user-images.githubusercontent.com/3895146/277397501-f65781ad-0006-495e-8d17-3aec9fe8f0b5.png"> Thanks.
> 
> Best wishes Teddy

Hi Teddy,

This was what I saw.
That is to say, the red-marked period is a data period with artefacts. And the pspm_scr_pp.m function should be able to detect this period and give me an output datafile with a variable "epoch". This "epoch" should contain the timing information of this red-marked data, for example, [5.0, 6.5] (note, this is not the real time points for this data, I am just taking it as an example).

However, after I called pspm_scr_pp, the output file contained a variable "epoch" which was empty. That is, scr_pp function did not realise that there was a period of data that were artefacts, i.e., scr_pp function did not detect the red-marked data period.

I hope this would be helpful.

Regards,
Yanfang

**Comment by teddychao** [comment]
This is now completed.
```
options = struct();
options.max = 100;
options.baseline_jump = 1.2;
options.clipping_window_size = 200000;
options.missing_epochs_filename = 'test26Feb2024';
options.clipping_step_size = 4000;
options.include_baseline = 1;
[sts, out] = pspm_scr_pp('.../tpspm_REW2_acq_0005_sn02.mat', options);
```
<img width="672" alt="image" src="https://github.com/bachlab/PsPM/assets/3895146/4f2da1d8-a769-4969-9cb0-1e2489237caf">
