### ISSUE TITLE
Implement new HPR model

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#579]
### Feature Description

Implement new HPR model based on Xia, Liu et al. (in preparation).

This requires:
- writing a new function `pspm_bf_hpr_rew` (model & parameters to be asked from Ted)
- implement as a `modelspec` in `pspm_init`
- implement in GUI

**Comment by SerenXia** [comment]
Actually, we have prepared "pspm_bf_hpr_rew" and "pspm_init" for the new Reward conditioning HPR model. Please find them attached (and you may want to adapt them to the current PsPM version). For example, the help texts need to be changed according to the actual codes in the function.
In the "pspm_bf_hpr_rew", we have implemented two RFs. They revealed no difference in our results. As RFs for the other modalities used a gamma function, we chose RF1. You may want to delete all relevant codes about RF2.

"pspm_init" contains the filter information for this new HPR.

Feel free to let me know if anything is unclear.

Best regards,
Yanfang

[pspm_implement_rew_hpr.zip](https://github.com/bachlab/PsPM/files/14586417/pspm_implement_rew_hpr.zip)
