### ISSUE TITLE
Problem running single-session DCM

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#587]
### Summary
DCM does not run from GUI.

### Steps to Reproduce
1. Use non-linear tutorial instructions

### Expected Results
Model runs through

### Actual Results
Model fails (see screenshot)
![image](https://github.com/bachlab/PsPM/assets/29309412/78364764-526c-4bce-9042-d92721c16e8c)

### (Optional) Possible Cause and Solutions
`pspm_check_model` wrongly turns a cell array of char into a cell array of cell arrays in line 209.

### Technical Info
* PsPM version: 6.1.1
* MATLAB version: 2023a

**Comment by teddychao** [comment]
Hi @dominikbach I have got the issue and try to complete tonight...
