### ISSUE TITLE
Bug in GUI for pspm_find_valid_fixations

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#604]
### Summary
Find valid fixation function: input arguments ("all eyes") do not match what are expected ("combined"); it also takes the first channel but not the last (all the other functions take the last channel) if multiple channels with the same name exist

**Comment by teddychao** [comment]
I am a little confused about the issue since I did not see `eye` was used in `pspm_find_valid_fixations`... I suspect this is because the old GUI has not been updated to be in line with the latest version of `pspm_find_valid_fixations`. I can update it but maybe discussion is useful.
