### ISSUE TITLE
Update logic of eyetracking preprocessing

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#609]
### Feature Description

Make sure all eyetracking preprocessing functions follow the same - or a similar - logic for determining which channels to work on.

This affects
- `pspm_find_valid_fixations`
- `pspm_pupil_pp`
- `pspm_pupil_correct_eyelink`

**Comment by SerenXia** [comment]
an additional note about this, specifying numeric channel number for pupil combining seems not work in the GUI (pspm function works). Here is the error message when I specify channel 24 as the "primary channel to preprocess" and channel 25 as the "secondary channel to preprocess and combine" in GUI Pupil processing:

Warning: options.channel has an invalid value. The allowed values are "pupil", "pupil_l", and "pupil_r". 
> In pspm_options>autofill (line 618)
In pspm_options (line 362)
In pspm_pupil_pp (line 143)
In pspm_cfg_run_pupil_preprocess (line 31)
In cfg_run_cm (line 29)
In cfg_util>local_runcj (line 1708)
In cfg_util (line 968)
In cfg_ui>MenuFileRun_Callback (line 705)
In gui_mainfcn (line 95)
In cfg_ui (line 53) 
Warning: options.channel_combine has an invalid value. The allowed values are "none", "pupil_l", and "pupil_r". 
> In pspm_options>autofill (line 618)
In pspm_options (line 364)
In pspm_pupil_pp (line 143)
In pspm_cfg_run_pupil_preprocess (line 31)
In cfg_run_cm (line 29)
In cfg_util>local_runcj (line 1708)
In cfg_util (line 968)
In cfg_ui>MenuFileRun_Callback (line 705)
In gui_mainfcn (line 95)
In cfg_ui (line 53)
