### ISSUE TITLE
Number of marker names and marker onsets mismatch in Eyelink import

### ISSUE THREAD

**Issue by eozd** [bachlab/PsPM#67]
### Summary
> I am not sure yet if this is a real bug but I noticed that the number of marker names and number of marker onsets mismatch after importing an eyelink asc file.

### Steps to Reproduce
1. Import an Eyelink `.asc` file containing some markers using `pspm_get_eyelink` function
2. Eyelink data file should contain markers with the following properties:
  * there is at least one marker whose timestamp is outside the timestamp range of the data samples
  * there are at least two markers whose timestamps are exactly the same

### Expected Results
> I expected that marker.values marker.names and data should have equal sizes.

### Actual Results
```MATLAB
struct with fields:
data: [2858×1 double]
markerinfo: [1×1 struct]
header: [1×1 struct]

        data{2}.markerinfo
        ans =
        struct with fields:
        name: {2860×1 cell}
        value: [2860×1 double]
```

### (Optional) Possible Cause and Solutions
> After comparing the imports from versions 4.0.2 with 4.2.0 I can see that that the first and last marker names (4.2.0) are not included in the cell arrays of marker names imported by the older pspm version.
I couldn't find anything in the pspm_trim.m file that takes into account these size differences. My guess is that it has something to do with the import_eyelink.m function and that some irrelevant eyelink messages are saved as marker names. However, I have not had the time to verify this with a different data set.

### A Possible Workaround Suggested in the original issue
> Please let me know if this is a valid work around or if I am seeing a bug where there is none.

PSPM v4.2.0
import_eyelink.m
line 259
```MATLAB
% construct markers
markers.markers = false(size(dataraw, 1), 1);
markers.times = [];
markers.names = {};
for idx = msg_indices
    msgline = messages{idx};
    parts = split(msgline);
    time = str2num(parts{2});
    markers.markers(bsearch(timecol, time)) = true;
    markers.times(end + 1, 1) = time;
    markers.names{end + 1, 1} = cell2mat(join(parts(3:end), ' '));
end
```

> My work around

```MATLAB
% construct markers
markers.markers = false(size(dataraw, 1), 1);
markers.times = [];
markers.names = {};
for idx = msg_indices
    msgline = messages{idx};
    parts = split(msgline);
    time = str2num(parts{2});
    % I have several cases where 2 markers times are identical although with
    % different names. Identical times become problematic in the next
    % step when we use them as index. This is my workaround so far...
    if ~isempty(markers.times) && time == markers.times(end)
        time = time+1;
    end
    % I am using ismeber instead of index = bsearch(x,var) here because
    % if the var that we are looking for is not included in the data vector
    % then index becomes max(x).
    i_search = find(ismember(timecol, time));
    if ~isempty(i_search)
        markers.markers(i_search) = true;
        markers.times(end + 1, 1) = time;
        markers.names{end + 1, 1} = cell2mat(join(parts(3:end), ' '));
    else
        %dont save time and name
    end
end
```
"""

### Technical Info
* Reference issue (original): https://sourceforge.net/p/pspm/tickets/17 
* PsPM revision ID: PsPM 4.2.0
* MATLAB version: R2017b

**Comment by eozd** [comment]
We first need to set up an Eyelink data file having the required properties as specified in the issue description. Then, we need to think about both of the current problems:
1. How to represent multiple markers on the same timestamp? It is not obvious how to implement this at first glance while also preserving the API of the function so that other PsPM parts, or previous code don't break
2. How to represent markers outside the time range of the data samples.

**Comment by irojkov-ph** [comment]
Dear Sasa,
I am currently working on this issue and yes you were right, there is actually a problem in our `import_eyelink` function. The problem I've noticed with the datasets you provided us is that:
- For dataset 1: the function imports all markers correctly but it also imports markers which are located beyond the `END` session marker and which are not supposed to be considered. For resolving this issue you can just replace corresponding lines by the following if statement:
```
if time < session_end_time
   markers.markers(bsearch(timecol, time)) = true;
   markers.times(end + 1, 1) = time;
   markers.names{end + 1, 1} = cell2mat(join(parts(3:end), ' '));
end 
```
- For dataset 2: there is another problem, in this data you have two consecutive markers at 2 distinct places and I guess that the `pspm_get_events` function (v.4.2.1) catches only one of the consecutive markers which causes the asymmetry between `data` and `markerinfo`. I am working on that right now.

P.S.: I have seen that on sourceforge you have replied to Tobias in an old bug report forum. May I ask you to create a new issue topic in github and develop your question.

**Comment by irojkov-ph** [comment]
Dear Sasa,
I want to inform you that I close this issue because:
1. the changes I've made in the pull request #73 solve the issue, i.e. PsPM will now catch all the markers in an Eyelink file within the `START` and `END` markers.
2. I've been informed that the case of multiple markers on the same timestamp is very unlikely such that it is the duty of the user to manage this cases. If more users encounter such a problem we will implement a new feature to treat such data. (I'm implementing a warning message to inform users that multiple markers have the same timestamp in the pull request #74)
