### ISSUE TITLE
SPM12 Data Import?

### ISSUE THREAD

**Issue by SANLAB-Bill** [bachlab/PsPM#68]
### Summary
Dear Dominik
Wondering if it is possible to import SPM12 data directly into PsPM 4.0.2? If not I can import as a matlab array as described in the manual but would appreciate any advice regarding importing the SPM12 event structure into PsPM.

Cheers

-Bill
### Technical Info
* PsPM revision ID:
* MATLAB version:

**Comment by irojkov-ph** [comment]
Dear Bill,
PsPM supports the SPM12 file format that you can use in various parts of the code e.g. `pspm_glm` or `pspm_sf`.
Why exactly are you asking this question ? What kind of data you want to import into PsPM and what kind of task do you want to perform on it using PsPM ?

Regads,
Ivan.

**Comment by SANLAB-Bill** [comment]
Many Thanks for your response Ivan. I have some data that includes both EEG and SCR, Respiration etc and wanted to import some channels into PsPM for analysis.

I ended just extracting the data from the SPM12 file and imported into PsPM in matlab format and then wrote a script to incorporate the event markers into the PsPM format data file. Seems to be working Ok but if there is a direct way to import SPM12 data into PsPM I’d appreciate a advice.

Many Thanks
-Bill

**Comment by irojkov-ph** [comment]
Dear Bill,
May I ask you to provide us a sample data ? It could help me to provide you a complete support. 
Thank you in advance,
Ivan

**Comment by dominikbach** [comment]
Hi Bill

PsPM can directly use SPM 12 multiple condition files, but no other data.

We could potentially design a direct import of psychophysiology data from SPM 12 if you send us a sample. It may however be easier to import these from their native (recording) format, depending on what that is.

Let us know if you need further support.

Best
Dominik
