### ISSUE TITLE
New GUI for PsPM 7.0

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#698]
### Feature Description

This is a draft for the new PsPM GUI. Feedback welcome. More background in #603 .
![PsPM GUI 20240419](https://github.com/bachlab/PsPM/assets/29309412/30ae0ea7-09b5-46b0-8a79-999388cf80ab)

We may get rid of the GUIDE-based GUI entirely and only use the mlapp.

**Comment by teddychao** [comment]
Hi @dominikbach 
Here is my design of PsPM UI for you to consider. The suggestion is mainly to simplify the UI and to place the most frequently used buttons on top for users. Thanks.
<img width="714" alt="image" src="https://github.com/bachlab/PsPM/assets/3895146/ea84b6bd-c60c-4b77-be67-8fd7a13ac942">

**Comment by dominikbach** [comment]
Perhaps the batch editor button could just be the same size as the other buttons? In the future, the box around the display & interactive editing items could then be expanded?

**Comment by teddychao** [comment]
Sorted...

<img width="715" alt="image" src="https://github.com/bachlab/PsPM/assets/3895146/729d4645-44bf-4eba-a13f-9517708cde50">
