### ISSUE TITLE
Errors while opening the toolbox

### ISSUE THREAD

**Issue by lomydkxq** [bachlab/PsPM#708]
### Summary
Errors appear. We may see below.

### Technical Info
* PsPM revision ID: PsPM v6.1.2
* MATLAB version: 2023a

**Comment by lomydkxq** [comment]
I've checked. It's 2023a recommended. However, there is still a lot of warning and error when I open the toolbox with `pspm`

**Comment by teddychao** [comment]
Hi @lomydkxq 
Thank you for posting the issue here.
Would you mind posting some screenshots of the issues so that we can provide further assistance for you?
Best wishes
Teddy

**Comment by lomydkxq** [comment]
@teddychao Thank you for the patience! I know it's bad without screenshots or log. I've just reinstall MATLAB just now.
Here's the log while opening the tool box with command `pspm`:

Unrecognized function or variable 'warntext_subfolder'.

Error in pspm_init (line 62)
  warning(warntext_subfolder);

Error in pspm_appdesigner/PsPM_OpeningFcn (line 62)
      pspm_init; % required for cfg_util('initcfg');

Error in pspm_appdesigner>@(app)PsPM_OpeningFcn(app,varargin{:}) (line 551)
      runStartupFcn(app, @(app)PsPM_OpeningFcn(app, varargin{:}))

Error in appdesigner.internal.service.AppManagementService/runStartupFcn (line 135)
            startupFcn(app);

Error in matlab.apps.AppBase/runStartupFcn (line 68)
            ams.runStartupFcn(app, startfcn);

Error in pspm_appdesigner (line 551)
      runStartupFcn(app, @(app)PsPM_OpeningFcn(app, varargin{:}))

Error in pspm (line 13)
      pspm_appdesigner

**Comment by lomydkxq** [comment]
And I don't think the warntext is a big problem? So I make the warning to text and more issues come out.

Failed to load E:\MATLAB\PsPM_v6.1.2\pspm_cfg\cfg_mlbatch_appcfg.m
Operands to the logical AND (&&) and OR (||) operators must be convertible to logical scalar values. Use the ANY or ALL functions to reduce operands to logical scalar values.
In file "E:\MATLAB\PsPM_v6.1.2\ext\matlabbatch\@cfg_branch\subsasgn_check.m" (v380), function "subsasgn_check" at line 22.
In file "E:\MATLAB\PsPM_v6.1.2\ext\matlabbatch\@cfg_branch\subsasgn.m" (v380), function "subsasgn" at line 80.
In file "E:\MATLAB\PsPM_v6.1.2\pspm_cfg\pspm_cfg_import.m" (???), function "pspm_cfg_import" at line 89.
In file "E:\MATLAB\PsPM_v6.1.2\pspm_cfg\pspm_cfg_preparation.m" (???), function "pspm_cfg_preparation" at line 11.
In file "E:\MATLAB\PsPM_v6.1.2\pspm_cfg\pspm_cfg.m" (???), function "pspm_cfg" at line 8.
In file "E:\MATLAB\PsPM_v6.1.2\pspm_cfg\cfg_mlbatch_appcfg.m" (???), function "cfg_mlbatch_appcfg" at line 20.
In file "E:\MATLAB\PsPM_v6.1.2\ext\matlabbatch\cfg_util.m" (v380), function "local_initapps" at line 1469.
In file "E:\MATLAB\PsPM_v6.1.2\ext\matlabbatch\cfg_util.m" (v380), function "cfg_util" at line 743.
In file "E:\MATLAB\PsPM_v6.1.2\pspm_appdesigner.mlapp" (???), function "pspm_appdesigner.PsPM_OpeningFcn" at line 63.
In file "E:\MATLAB\PsPM_v6.1.2\pspm_appdesigner.mlapp" (???), function "@(app)PsPM_OpeningFcn(app,varargin{:})" at line 551.
In file "E:\MATLAB\R2023a\toolbox\matlab\appdesigner\appdesigner\runtime\+appdesigner\+internal\+service\AppManagementService.m" (???), function "AppManagementService.runStartupFcn" at line 135.
In file "E:\MATLAB\R2023a\toolbox\matlab\appdesigner\appdesigner\runtime\+matlab\+apps\AppBase.m" (???), function "AppBase.runStartupFcn" at line 68.
In file "E:\MATLAB\PsPM_v6.1.2\pspm_appdesigner.mlapp" (???), function "pspm_appdesigner.pspm_appdesigner" at line 551.
In file "E:\MATLAB\PsPM_v6.1.2\pspm.m" (???), function "pspm" at line 13.

**Comment by lomydkxq** [comment]
When I try to use 'Data Preparation - import', the import window does not come out with error:

One or more output arguments not assigned during call to "varargout".

Error in cfg_add_module (line 6)
mod_job_id = cfg_util('addtojob', cjob, mod_cfg_id);

Error in pspm_appdesigner/button_data_preparation_Callback (line 175)
          cfg_add_module('pspm.prep.import');

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating DropDown PrivateValueChangedFcn.

**Comment by teddychao** [comment]
Hi @lomydkxq 
Thank you for posting the details described above.
Would you mind trying starting pspm by typing `pspm_guide` and see if the issue related to `Unrecognized function or variable 'warntext_subfolder'.` still appears?
I look forward to hearing from you.
Best wishes
Teddy

**Comment by lomydkxq** [comment]
Thank you! @teddychao 
It still exists. And I installed the toolbox manually, by downloading the zip, extracting it, and 'set path - add with subfolders...' I don't know if this way is correct


PsPM: loading defaults ... 
Unrecognized function or variable 'warntext_subfolder'.

Error in pspm_init (line 62)
  warning(warntext_subfolder);

Error in pspm_guide>PsPM_OpeningFcn (line 54)
  pspm_init;

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in pspm_guide (line 44)
    gui_mainfcn(gui_State, varargin{:});

**Comment by lomydkxq** [comment]
The warntext problem is not that important? Because I can change the warning to the text. 

But the following issues do matter. I don't know whether it is because I wrongly run or install the toolbox. Or I don't know if they are related.

**Comment by lomydkxq** [comment]
@teddychao Hi! I did in windows system. My installation steps are just same as your recommendation.

**Comment by lomydkxq** [comment]
When I try to import. No other windows come out. With error:
`One or more output arguments not assigned during call to "varargout".

Error in cfg_add_module (line 6)
mod_job_id = cfg_util('addtojob', cjob, mod_cfg_id);

Error in pspm_appdesigner/button_data_preparation_Callback (line 175)
          cfg_add_module('pspm.prep.import');

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating DropDown PrivateValueChangedFcn.`
![image](https://github.com/bachlab/PsPM/assets/65751998/356db84f-92a0-4190-b0ba-6d1acb40b08b)

**Comment by teddychao** [comment]
Hi @lomydkxq 
Thank you for providing the screenshots and the additional information.
I am not sure if my understanding is correct. May I confirm with you that, the warnings related to `warntext_subfolder` appear when PsPM was started up, and the warnings related to `One or more output arguments not assigned during call to "varargout".` appear when the feature `import` was called?
We have also a Windows PC and we can run PsPM here. 
![image](https://github.com/bachlab/PsPM/assets/3895146/4e2bff46-3710-4b87-a707-4cc1eede7c53)

We are looking at the error records and trying to replicate the issue. It has not been very clear to us about how the issue was caused since PsPM can be run on Window 10 and MATLAB 2019 here without problem.
Thank you for your patience.
Best wishes
Teddy

**Comment by lomydkxq** [comment]
@teddychao Thank you for the patience!
Your understanding is all correct. The `warntext_subfolder` doesn't come to an error is because I modify the source code to warn a text instead of that vairable.
![1715613459759](https://github.com/bachlab/PsPM/assets/65751998/0dcd3443-07e7-4145-af7e-8ee101ef140c).

And yes, when the toolbox started up, the logic porblem shows including
![image](https://github.com/bachlab/PsPM/assets/65751998/de77bb28-062d-4372-b86d-8e6913444664)

And I tried to import, the further error `One or more output arguments not assigned during call to "varargout"` comes.

Now I am trying to install MATLAB2019 and get back to you soon.

Thank you so so much!

**Comment by lomydkxq** [comment]
@teddychao hello!

Finally I solved the problem. It is your instruction `Open MATLAB, locate to the PsPM root folder` that reminds me. I tried with `Add folder` instead of `Add with subfolders..` when I `Set path` and then succeeded. It seems their might be some collision on function names in subfolders. But it is not a big problem.

![image](https://github.com/bachlab/PsPM/assets/65751998/df7443ac-36a3-4140-a2e2-37fee6501caf)


Thank you for so much patience anyway!

**Comment by XiaochenZhou23** [comment]
Hi @teddychao, I encountered the same problem here:

**Technical Info**
- PsPM revision ID: PsPM v6.1.2
- MATLAB version: 2023b
- System: macOS

And I followed the process:
1. Download PsPM from https://github.com/bachlab/PsPM/releases/tag/v6.1.2. And I select [PsPM_v6.1.2.zip].
2. After downloading process completed, I uncompress it.
3. Open MATLAB, locate to the PsPM root folder (I've tried either with `Add folder` or `Add with subfolders..`).
4. In the command window, type `pspm`.

The error messages are totally similar to @lomydkxq.
1. After `pspm`: `Unrecognized function or variable 'warntext_subfolder'.` And I've change the code from `warning(warntext_subfolder)` to `warning('warntext_subfolder')`. It then `Failed to load ../MATLAB/PsPM_v6.1.2/pspm_cfg/cfg_mlbatch_appcfg.m Operands to the logical AND (&&) and OR (||) operators must be convertible to logical scalar values. Use the ANY or ALL functions to reduce operands to logical scalar values.`
2. When I try to import (data preparation): No windows come out, with error `One or more output arguments not assigned during call to "varargout".`
<img width="1440" alt="截屏2024-05-18 16 37 06" src="https://github.com/bachlab/PsPM/assets/147261686/b0b8b8bb-c8db-4590-8862-d470825d21c7">

Would you mind help me to find our what's wrong here 😢

**Comment by lomydkxq** [comment]
Please See the `set path` on the top, delete all the path related to pspm, `add path ` agian instead of `add with subdir'. Could you try again?

**Comment by lomydkxq** [comment]
@XiaochenZhou23 Anyway, I think we both have WeChat, could you add me with WeChat: 13671133049?
