### ISSUE TITLE
Bug in `pspm_data_editor` 

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#748]
Argument `handles.options` is not initialised if not provided as an input.
Thus, writing the output fails. 

Solution:
initialise `handles.options = struct()` and then run through `pspm_options` if not provided as input.

Error information:
```

Unrecognized field name "options".

Error in pspm_data_editor>CreateOutput (line 202)
        ow = pspm_overwrite(out_file, handles.options.overwrite);

Error in pspm_data_editor>pbApply_Callback (line 923)
if CreateOutput(hObject) == 1

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in pspm_data_editor (line 50)
  gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)pspm_data_editor('pbApply_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.
```

**Comment by teddychao** [comment]
I think these two overwrite actions shall be always to overwrite. This two lines of code will only be called when users want to write the files. If there have been files with the same name, PsPM will ask users to confirm if then want to replace. I have updated the PR.
