### ISSUE TITLE
Graphing the Canonical Response Function

### ISSUE THREAD

**Issue by bvoogd** [bachlab/PsPM#76]
Hello,

I am attempting to graph the canonical response function described in Appendix A of the article _Modelling event-related skin conductance responses_.  My MATLAB code to graph it is as follows:

    syms x;
    syms N(t);
    syms E(t);
    N(t) = (1/sqrt(2*pi*0.7013))*exp((-(t-3.0745)^2)/(2*(0.7013^2)));
    E(t) = exp(-0.3176*t) + exp(-0.0708*t);
    CRF = int(N(t-x)*E(x),x,-inf,inf);

I've attached the resulting graph to this post.  It has the tail that I expected but does not have a sharp rise at the beginning.  Can you confirm that I'm following the equation from Appendix A correctly?

Thanks,
Ben
<img width="477" alt="CRF" src="https://user-images.githubusercontent.com/1429651/70001750-f4dde980-1512-11ea-8b44-6bba7eefad96.png">

**Comment by dominikbach** [comment]
Hi Ben.

thanks for reaching out. There is a typo in this equation, in that the lower integration limit should be 0. See for reference "Historical remark" (a) on p. 17 of the PsPM 4.2.1 manual.

PsPM is using Matlab's vector convolution which approximates integrating over [0, inf], i.e.
CRF = int(N(t-x)*E(x),x,0,inf);

Hope this helps.
Best
Dominik

**Comment by dominikbach** [comment]
Plotted CRF using the code from above with lower integration limit at zero:
![image](https://user-images.githubusercontent.com/29309412/70139346-2e853080-168a-11ea-9cc4-4c8c3da65871.png)
