### ISSUE TITLE
Variational Bayes Algorithm with the Canonical Response Function

### ISSUE THREAD

**Issue by bvoogd** [bachlab/PsPM#77]
Hello,

I have a question about the use of the Variational Bayes Algorithm (VBA) from Appendix A of the article _Dynamic causal modelling of anticipatory skin conductance responses_. If I understand correctly, the VBA is used to estimate the parameters for the individual RF of each participant. If a user chooses to use the canonical RF, where those parameters are predetermined, it seems to me that VBA would no longer be required. Does PsPM use VBA with the cRF?

Thanks,
Ben

**Comment by dominikbach** [comment]
Hi Ben

thanks for reaching out.

VBA was used to estimate parameters for the canonical response function in ODE form. These pre-defined parameters are used to model the CRF.

Primarily, however, VBA is used to estimate the trial-by-trial parameters of the neural input into the system in terms of amplitude, for aSCR and SF also timing, and for aSCR also dispersion.

Hope this helps.
Dominik

**Comment by bvoogd** [comment]
Hi Dominik,

Thank you very much for your response, it helps me understand what VBA is used for. I had assumed that you could estimate the neural input parameters by deconvolving the SC data with the CRF. Could you please explain why you use VBA to estimate amplitude, timing, and dispersion rather than the deconvolution procedure?

Thanks,
Ben

**Comment by dominikbach** [comment]
Hi Ben

VBA is used as a deconvolution algorithm - given a known RF it estimates the most likely input under some constraints. 

There are certainly many other deconvolution procedures which make different assumptions about the input, the RF, and the noise structure.

Hope this helps.
Dominik
