### ISSUE TITLE
Allow GLM to use markers distributed across channels

### ISSUE THREAD

**Issue by irojkov-ph** [bachlab/PsPM#84]
### Feature Description
Currently whenever the timeunit of the timing variable is 'markers',  `pspm_glm` uses only one marker channel which can be specified by `options.marker_chan_num` variable. A user of PsPM suggested that it could be useful to be able to use markers distributed across channels.

**Comment by hohxil-kathy** [comment]
Is this solved in v4.3.0? It seems that v4.3.0 still allows only one marker channel.

**Comment by teddychao** [comment]
> Is this solved in v4.3.0? It seems that v4.3.0 still allows only one marker channel. 

Hi @hohxil-kathy 

Sorry I'm afraid this feature is still in progress. We are going to add this feature in a future release.

Thanks
Teddy
