### ISSUE TITLE
Transfer Function - Biopac settings

### ISSUE THREAD

**Issue by mijdar** [bachlab/PsPM#85]
### Summary
Hi there,

I am trying to figure out how to get the absolute values for SCR when importing files in PsPM using the "Transfer Function". We are using Biopac to record the data. Where do I get the values for the recording settings for Biopac?

Thanks in advance.

**Comment by Noldos** [comment]
Hi mijdar,
Assuming acknowledge was configured correctly at the time of recording, data is natively recorded in uS and doesn't need any scaling. From the top of my head, transfer function parameters would be a=0, b=0, c=1

**Comment by mijdar** [comment]
Hi Noldos,

I am assuming:

a = Series resisor
b = Offset
c = Transfer Constant

is this correct?

In batch, when I try these settings:

Transfer constant = 1
Offset = 0
Series Resistor = 0

I still get the same relative values as when using Transfer Function = None.

Any thoughts?

**Comment by mijdar** [comment]
To clarify, do not want negative values.

**Comment by dominikbach** [comment]
Hi Mijdar

yes, you should be getting the exact same values (as we assumed you had recorded in uS) - the only thing that changes is the internal representation of the units.

Negative values may indicate that the device was not configured to record in uS, and then unfortunately I cannot say from here what the correct transfer constants are. You can always put several known resistors into the circuit and find out (but I seem to remember that with an improperly configured system you may be getting a non-linear transfer function). But unfortunately we cannot provide hardware support - please contact biopac in this case.

Hope this helps
Dominik
