### ISSUE TITLE
trial-by-trial analysis / deconvolution of signals

### ISSUE THREAD

**Issue by defaultuzer** [bachlab/PsPM#86]
### Summary

Dear everyone, 

We recently collected a lot of physiological data (SCR, HR, breathing, pupil diameter) and would like to analyze it on a trial-by-trial basis with the PsPM toolbox. 

Specifically, we would like to recover one 'psychological' value per stimulus from our physiological output signals i.e. solving the inverse inference problem. 
The question is whether the PsPM toolbox offers an inversion or a deconvolution method that can recover fear levels as rated by the participants (here, our 'ground truth') from our physiological recordings. 

Our design was very straight forward with the following order: fixation cross (3-5s jitter), spider stimulus (5s), fear-rating (no fixed time) which resulted in interstimulus intervals of roughly 4 – 7 seconds. 
We already tried a GLM-based weight estimation of each trial (each individial stimulus onset as a regressor) but are not sure how legitimate this is in such a fast-paced design. 

We're fairly new to physiological data modelling and also to the PsPM toolbox and hence would be very grateful about some advanced input. 

Thanks for any input and best regards!

### Technical Info
* PsPM revision ID: Version 4.2.1
* MATLAB version: MATLAB R2018a

**Comment by dominikbach** [comment]
Der all

thanks for getting in touch.

PsPM can be used to estimate an "arousal" value per trial and per measurement modality (data source). 

At present, there is no formal model to combine different data modalities, or to directly estimate subjective "value" from data.

For analysing individual data modalities, best follow the manual.

Hope this helps
Dominik

**Comment by defaultuzer** [comment]
Dear Dominik, 

thanks a lot for your answer, it is highly appreciated.

"PsPM can be used to estimate an "arousal" value per trial and per measurement modality (data source)." 
--> this is precisely what we would like to do, looks like we posed the question in a sub-optimal way. Sorry for that, maybe caused by a jointly written question..  

Maybe to make it more clear: we would like to detect e.g. one SCR amplitude (or HR measure) for each stimulus shown from a database and ultimately try to find a "typical" physiological value for said stimuli also across participants. 

However, the only way we understood to do this so far (after going through the manual) is to do a GLM - as described above by modelling each trial as a seperate condition (or DCM in SCR). 
In the case of a fast-paced design like ours, wouldn't this lead to a questionable interpretability of the single estimation parameters per trial due to the lagged responses of the measurement modalities (presumably the more concerning, the slower the response of the modality e.g. breathing)? 
Or is this of no concern with the described ISI when using a GLM? 

Hopefully the question/concern is more clear now. 

Thanks again for any help!

Best regards, 
Sebastian

**Comment by dominikbach** [comment]
Hi Sebastian
for SCR you can use GLM and DCM. They make different assumptions, I don't know the literature on 5-s image presentations too well (e.g. are the SCR time-locked to image onset or do they (sometimes) occur later.
For HPR, there is generally a lack of knowledge on stimulus-related response patterns, even more so for a 5-s paradigm. I'm aware of some papers from the Florida group, summarised e.g. in our paper on the HPR model development (Paulus et al. 2016) which is notably a model for brief external events (like the SCR-GLM).
For breathing, there is almost no data on stimulus presentations of that sort (see Bach et al. 2016 for a summary of the literature), so here it may be very interesting to just see interpolated and averaged data time series (for which you can use PsPM).
There is much work on pupil dilation but as far as I'm aware no validated formal model for stimulus-induced responses (see Korn & Bach 2016 for literature summary).
Hope this helps
Dominik
