### ISSUE TITLE
Check structure of subfolders of scr

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#97]
### Feature Description

Subfolders of scr appear unsystematic. Can they be organised systematically?

**Comment by eozd** [comment]
The current folders containing external libraries we use are listed below:

1. `src/SPM`
2. `src/VBA`
3. `src/amri_eegfmri`
4. `src/matlabbatch`
5. `src/backroom/bsearch`
6. `src/pupil-size`

**Comment by irojkov-ph** [comment]
I close the issue since it is fixed with the 4.3.0 release.
